### ISSUE TITLE
Setup some CI

### ISSUE THREAD

**Issue by parsonsmatt** [fourmolu/fourmolu#11]
Travis is easy and familiar to me but maybe it's a good time to try Circle CI

**Comment by kahlil29** [comment]
We use CircleCI for our Haskell projects at work and I think I could help with this.

**Comment by georgefst** [comment]
That would be great! I don't have much experience with this stuff, but I don't imagine Fourmolu needs anything special. It may be worth looking at what Ormolu does.

Worth noting that, as I'm not able to install Stack or Nix on the only machine I have access to at the moment, those workflows may well be broken...

**Comment by parsonsmatt** [comment]
Yeah, I'd like to have a vanilla Cabal workflow that's checked, as well as stack. I do not care about nix so I don't mind if that goes by the wayside, though if someone does want to support it, I'd be happy to accept those PRs :)

**Comment by andreabedini** [comment]
Would you consider GitHub Actions? I have recently prepare a workflow for [haskey](https://github.com/haskell-haskey/haskey/blob/master/.github/workflows/ci.yml) which would be easy to replicate for fourmolu. It tests both cabal & stack.

**Comment by expipiplus1** [comment]
Automatic merging of ormolu changes could be very convenient to keep things up to date.
