### ISSUE TITLE
Disable output of "Loaded config from: <path>"?

### ISSUE THREAD

**Issue by kenranunderscore** [fourmolu/fourmolu#110]
When loading a custom configuration in `fourmolu.yaml`, the above string is written to `stderr`. I'd like to be able to disable this (maybe via CLI option), as it interferes with my tooling - even though the tooling should in my opinion also be able to handle this better. The following is what I'm having problems with:

`haskell-mode` for Emacs has a configuration option to set the formatter, which I set to `fourmolu`. It then starts a background process, capturing `stdout` and in the success case, it overwrites the buffer contents with that. But it also captures `stderr` and in the case that the corresponding file is non-empty, it fails altogether and won't format the buffer. I think it's worth for me to try and fix that upstream by checking the error code with precedence over the `stderr` file, but it's maybe also worth making it configurable in `fourmolu` (or something else entirely).

Or maybe not writing to `stderr` in the success case is the right call? The effects of introducing/changing a configuration file should be immediately visible or at least easily observable.

In case you think something could/should be done here, kindly let me know and I'll see if I can make a PR out of it :)

**Comment by kukimik** [comment]
Some CLI tools have a `--verbose`/`--quiet` flag. If any warnings or diagnostic messages are added to `fourmolu` in the future, they could be enabled/disabled using such a flag.

**Comment by georgefst** [comment]
Seeing the message can be very useful to explain any unexpected behaviour, so I'd prefer it on by default, but I could consider a flag. OTOH, feels to me like `haskell-mode` is at fault here. Have you opened an issue there?

**Comment by kenranunderscore** [comment]
I've done so now. Sorry, it was late yesterday and I wanted to check for a local solution first.
