### ISSUE TITLE
Better documentation of formatting options

### ISSUE THREAD

**Issue by georgefst** [fourmolu/fourmolu#111]
We ought to explain more clearly what each option does, with a side-by-side comparison of a minimal example. We could also explain why one might prefer one setting over another.

For now, this should probably exist as a markdown document in this repo, separate from the README.

**Comment by georgefst** [comment]
Make sure to tackle #56.

**Comment by georgefst** [comment]
@brandonchinn178 has made significant improvements to this documentation since this issue was opened. And #239 improves things further. But I still think it would be best to see nicely marked-up simple examples right there next to the descriptions. Trawling through the test suite is a lot more work.

**Comment by brandonchinn178** [comment]
I believe the website has good docs for formatting options now 😄
