### ISSUE TITLE
Add a rule about comment spacing

### ISSUE THREAD

**Issue by dmarticus** [fourmolu/fourmolu#118]
As far as I can tell, there's no good tool for catching missing spaces after comments in Haskell.  For example, when code reviewing, I sometimes see things like this:
```
--this is a comment
```

when I think most folks would prefer 
```
-- this is a comment
```

This type of comment isn't super fun to make in code reviews, since it's more of a nit than anything, and it seems like something that should be enforced by a linting/formatting tool.  Other formatters, such as [eslint](https://eslint.org/docs/rules/spaced-comment) and [SwiftLint](https://realm.github.io/SwiftLint/comment_spacing.html) have such rules, and it'd be awesome if fourmolu could support something similar.

Let me know if there's anything helpful I can add to this issue!

**Comment by brandonchinn178** [comment]
Related: https://github.com/fourmolu/fourmolu/issues/212

**Comment by brandonchinn178** [comment]
This should be fixed now!
