### ISSUE TITLE
Merge Ormolu 0.4.0.0

### ISSUE THREAD

**Issue by georgefst** [fourmolu/fourmolu#126]
We're up to date with the latest release, so this is really just a placeholder for now.

The re-implementation of Ormolu Live is interesting. I'm not sure if we'll get something similar for free (other than the need to host it etc.) or whether it's heavily Nix-dependent.

**Comment by georgefst** [comment]
This will also give us #136.

**Comment by georgefst** [comment]
[It's here](https://github.com/tweag/ormolu/releases/tag/0.4.0.0).

**Comment by dmarticus** [comment]
Woohoo!  Thank you!

**Comment by georgefst** [comment]
Closed by #138.
