### ISSUE TITLE
Preserve Unicode Syntax

### ISSUE THREAD

**Issue by vherrmann** [fourmolu/fourmolu#134]
I'd like fourmolu to preserve my beautiful ∀s. 

I think it should either get a config option like `respect-unicode-syntax`, it should leave ∀s always alone or the behavior could be made dependent on the option `respectful`.

**Comment by georgefst** [comment]
I'd accept a PR that puts it behind `--respectful`. Won't be trivial to implement though - both `∀` and `forall` show up the same in GHC's AST except for `SrcSpan`s.
