### ISSUE TITLE
Allow configuring indentation of "in" after "let" block

### ISSUE THREAD

**Issue by bapcyk** [fourmolu/fourmolu#152]
![image](https://user-images.githubusercontent.com/14261219/153221006-7db4be6d-0bbd-4a82-8b51-5bfca07c78de.png)

`in` is shifted to 1 space, how to shift it to indentation * N, where N=0, 1, ... ? TBH 0 would be better :) Is it possible? Because currently it is not multiple of indentation.

**Comment by brandonchinn178** [comment]
That's not currently configurable. But yes, we could add that configuration

**Comment by brandonchinn178** [comment]
Also related: #83
