### ISSUE TITLE
How to make the instance's function vertically more compact ?

### ISSUE THREAD

**Issue by bapcyk** [fourmolu/fourmolu#154]
![image](https://user-images.githubusercontent.com/14261219/153422958-da3c495a-7c73-4bd1-b955-cf74c48c53f4.png)

How to make `genericParseJSON defaultOptions` on the same line - together with `=` ? Is it possible?

**Comment by brandonchinn178** [comment]
To be clear, you're asking about keeping the following format, right?

```hs
instance FromJSON RawSettings where
  parseJSON = genericParseJSON defaultOptions
    { fieldLabelModifier = \case
        '_' : s -> s
        s -> s
    }
```

This isn't currently possible, but it also doesn't seem very generalizable. For example, this doesn't seem very readable to me:
```hs
foo = bar x0 x1 x2 x3 x4 defaultOptions
  { a = 1
  , b = True
  }
```
keeping the record update close to the thing being updated makes it clearer to see what's happening.

**Comment by brandonchinn178** [comment]
Closed as wontfix because of no response
