### ISSUE TITLE
Comment starting with pipe followed by two empty comments causes error

### ISSUE THREAD

**Issue by Geometer1729** [fourmolu/fourmolu#157]
running `fourmolu tmp.hs`  

with this code in tmp.hs :
```haskell
module Tmp where

-- | Some comment that starts with a pipe
--
--
-- and is followed by two blank comments

x :: Int
x = 5
```
results in this output
```
AST of input and AST of formatted code differ.
  at tmp.hs:(3,1)-(6,40)
Please, consider reporting the bug.
```
here's the `--version` output:
```
fourmolu --version
fourmolu 0.3.0.0 UNKNOWN UNKNOWN
using ghc-lib-parser 8.10.5.20210606
```

**Comment by Geometer1729** [comment]
```haskell
module Tmp where

{- | Some comment that starts with a pipe


 and is followed by two blank comments
-}
x :: Int
x = 5
```
Block comments seem to have have the same problem.

Deleting the `--` from the blank lines or deleting one of the blank comments are both workarounds for this.

**Comment by brandonchinn178** [comment]
This doesn't seem to be an issue anymore (fourmolu is currently on 0.6.0.0). Can you try upgrading?

**Comment by Geometer1729** [comment]
Yup, at least In the current commit 6edfa3b33159766b3f13e8e330c864bd6999a090 it seems to be fixed :+1:
