### ISSUE TITLE
Include binaries in releases

### ISSUE THREAD

**Issue by kk-hainq** [fourmolu/fourmolu#159]
We love `fourmolu` and use it for several projects. It would be quite convenient if there were pre-built binaries included in the releases for quick fetching and usage in, say, GitHub workflows. We are willing to help set up a workflow for it here if accepted!

**Comment by georgefst** [comment]
Yeah that would be nice to have!

We'd accept it as long as it's easy for the current maintainers to maintain, or if you'd commit to making any necessary updates yourself. We're running a bit low on resources already, as seen by the number of unmerged PRs. And I wouldn't personally use them myself, as I use the Fourmolu binary from the Arch community repo, as well as the version bundled in the Haskell Language Server (and being a maintainer, I'm often building it locally as well anyway).

It would be cool to port Ormolu's Nix config. But I don't know that any of our current maintainers (basically me and @brandonchinn178) are comfortable enough with Nix to make that a good idea.

**Comment by brandonchinn178** [comment]
Pre built binaries would also be cool on my end! @kk-hainq if youd be willing to own that, thatd be great. If not, I can try to see if I have time to configure that.

I'm certainly not qualified to maintain nix stuff (personally, im a bit anti-nix) but if someone wants to own that, i wouldnt be opposed to keeping the nix stuff in the repo

**Comment by kk-hainq** [comment]
We can definitely put something together without Nix! Will GitHub Actions work for you, or should we just extend the CircleCI setup?

**Comment by brandonchinn178** [comment]
I would probably prefer circle ci, to keep all the builds the same and in one place.

Note that it should just be a matter of building the executables + storing them as "artifacts" (see circleci docs) that one could download later. Then the Release section in DEVELOPER.md should be updated to mention downloading the binaries + attaching them to the github release

**Comment by kk-hainq** [comment]
Awesome! If we could help with the CI setup can you help with the releases?

**Comment by brandonchinn178** [comment]
I'm not quite sure what you mean by helping with the releases. Are you asking to attach binaries for the current version?

**Comment by kk-hainq** [comment]
Not necessarily the current one but yes, attaching binaries to the upcoming releases :).

**Comment by brandonchinn178** [comment]
Yes; just update the `DEVELOPER.md` file like I described, and when we release future versions, we'll follow that checklist to attach the binaries
