### ISSUE TITLE
HLint-style named configurable rules

### ISSUE THREAD

**Issue by tysonzero** [fourmolu/fourmolu#165]
Our project differs in a wide variety of ways from the default fourmolu configuration (and the ormolu config). For many of those I prefer the way our codebase looks over the suggested code.

With hlint the ergonomics of this are quite nice, you can automatically ignore all the rules that the code currently breaks. I additionally appreciate how it tells me exactly what parts of the code are wrong and why, without having to diff the output and compare.

Supporting something fairly equivalent would be fantastic, and would make it much more practical for us to start using fourmolu as part of our CI.

I will additionally look through the diffs and suggest specific configuration options for the differences I noticed, but I thought I would start by suggesting this more systematic solution.

**Comment by georgefst** [comment]
I can sympathise, but I think this may be _very_ difficult to implement. HLint has a totally different architecture. Fourmolu doesn't have an easily-enumerable set of "rules" which get applied to snippets of the source. Instead it pretty-prints the whole AST at once.

It may be that `{- FOURMOLU_DISABLE -}` pragmas are the best we can do, and I aprreciate that's probably not satisfactory.

**Comment by tysonzero** [comment]
Thanks for the quick feedback!

In that case I'll raise some issues for the differences between our code and the pretty printing that I want to preserve.

In case they end up being rather difficult to resolve, do you have suggestions for a more lenient/rules-based formatting linter? Honestly it's fine if it doesn't even auto format, I just want it for CI.

**Comment by tysonzero** [comment]
I think #166 #167 and #168 should more or less cover all the situations our codebase disagrees that I would like to preserve.

**Comment by georgefst** [comment]
> In case they end up being rather difficult to resolve, do you have suggestions for a more lenient/rules-based formatting linter? Honestly it's fine if it doesn't even auto format, I just want it for CI.

I'm not sure if any of the Haskell formatters are architected that way. Maybe Stylish-Haskell? I'm fairly sure it's the least opinionated, anyway.

**Comment by tysonzero** [comment]
Yeah stylish-Haskell does seem the least opinionated, we will most likely use it in the meantime. Although if the three linked issue do end being solved we’ll switch to fourmolu.

**Comment by tysonzero** [comment]
After further research it looks like most of `stylish-haskell` is also too opinionated, so we might be out of luck when it comes to an off-the-shelf code formatting solution.

**Comment by brandonchinn178** [comment]
Copying comment from #167:
> > What I really want is closer to a "formatting linter" that doesn't necessarily know how to automatically fix formatting violations, but just spits them to stdout and throws an error for CI.
>
> I'm not aware of anything like this in any other language (I know of prettier and black, and they don't do this). In general, I'm not sure how you'd even configure "formatting violations". If you really want something like this, you could build your own tooling that runs fourmolu, grabs the diff, and selectively ignore diffs you don't care about. But fourmolu will probably not support the workflow you're thinking of.

I'm going to close this issue, as Fourmolu will not support the workflow of selectively formatting things, outside of `FOURMOLU_DISABLE` pragmas (which isn't supported in any other code formatter I know of)
