### ISSUE TITLE
Allow middle ground between one-liner and maximum-lines

### ISSUE THREAD

**Issue by tysonzero** [fourmolu/fourmolu#166]
There is currently no middle ground between the following:

```
foo = bar baz [longer, argument]

foo =
    bar
        baz
        [ longer
        , argument
        ]
```

However I would like to be able to do:

```
foo = bar baz
    [ longer
    , argument
    ]
```

I think allowing for this style fits particularly well with Haskell's currying mantra. As `foo bar` is really no different from `fooBar = foo bar`.

This comes up quite frequently in our codebase due to our use of Miso's html DSL, where the first argument for attributes is usually much shorter than the second for child nodes, and can often comfortably fit on the same line.

The current formatting leads to a lot more vertical and horizontal space usage.

This mostly comes up for functions with multiple arguments, but it also comes up sometimes with operator usage:

```
foo = bar $ baz <&> \x ->
    qux x

foo =
    bar $
        baz <&> \x ->
            qux x
```

**Comment by tysonzero** [comment]
Unsure if it should be considered a separate issue/option or not, but on the same note:

```
data Foo = Foo
    { bar :: Int
    , baz :: Text
    , qux :: Bool
    } deriving (Eq, Show)

data Foo = Foo
    { bar :: Int
    , baz :: Text
    , qux :: Bool
    }
    deriving (Eq, Show)
```

Being able to keep the former would be nice.

**Comment by georgefst** [comment]
This is at least closely-related to #46.

**Comment by brandonchinn178** [comment]
This is also more an Ormolu issue: https://github.com/tweag/ormolu/issues/692
