### ISSUE TITLE
Put 'where' on same line as ')' in a multiline module export list

### ISSUE THREAD

**Issue by tysonzero** [fourmolu/fourmolu#167]
Similar to how leading comma lists have the parenthesis lead as well, it'd be nice to allow this for imports and exports:

```
module Foo
    ( bar
    , baz
    , qux
    ) where

import Foo
    ( bar
    , baz
    , qux
    )
```

**Comment by brandonchinn178** [comment]
isn't this configurable via `diff-friendly-import-export: false`?

**Comment by tysonzero** [comment]
Oh that is closer than I thought:

```
module Foo
    ( bar
    , baz
    , qux
    )
where

import Foo
    ( bar
    , baz
    , qux
    )
```

Only differing thing is the `where` positioning.

**Comment by brandonchinn178** [comment]
Is the `where` positioning of high value to you? While Fourmolu aims to be a configurable formatter, it will never aim to be a maximally configurable formatter. At some point, Fourmolu will be making some decisions that you (or I) might not agree with, but that's what you get with a formatter. IMO, where the `where` goes is a rather minor detail that isn't worth adding a configuration option for.

**Comment by tysonzero** [comment]
Fairly important yeah. Avoiding constructs that I think look weird is like 90% of why I want to put a formatter in our CI process. `where` on the same column as the parent construct is normally a syntax error, so it just feels weird seeing it there even though it's legal in this case.

Yeah it's definitely looking quite difficult to find a true "formatter" that meets my needs. What I really want is closer to a "formatting linter" that doesn't necessarily know how to automatically fix formatting violations, but just spits them to stdout and throws an error for CI. That way it can presumably be significantly more configurable, like `hlint` is.

**Comment by brandonchinn178** [comment]
Oh, sorry, I wasn't aware that that output is what Fourmolu (and Ormolu) does currently. Yes, I do wonder why Ormolu does it that way. I opened an issue asking upstream: https://github.com/tweag/ormolu/issues/876; I suspect that Ormolu will not want to change it, in which case, I think it makes sense to add a configuration option for this.

In other words:
1. If Ormolu closes that issue, this issue should be to put `where` on the previous line
2. If Ormolu fixes it, I'll just close this issue (I can't imagine anyone wanting to configure `where` to be on the next line)

I'll rename this issue in anticipation of (1)

> What I really want is closer to a "formatting linter" that doesn't necessarily know how to automatically fix formatting violations, but just spits them to stdout and throws an error for CI.

I'm not aware of anything like this in any other language (I know of prettier and black, and they don't do this). In general, I'm not sure how you'd even configure "formatting violations". If you really want something like this, you could build your own tooling that runs fourmolu, grabs the diff, and selectively ignore diffs you don't care about. But fourmolu will probably not support the workflow you're thinking of.

**Comment by Bodigrim** [comment]
@brandonchinn178 any chance to implement this on `fourmolu` side please? This has been a stumbling point for me.

**Comment by brandonchinn178** [comment]
My first preference would be to get more discussion with @mrkkrp in tweag/ormolu#876, and figure out if Ormolu is interested in this change, or if not, why Ormolu doesn't want this style. @Bodigrim if you can try to spur conversation in the upstream issue, that would be super helpful.

This first step is preferable because it means we can just have this change without adding a new config option.

If Ormolu is not interested in making this change and/or you want to skip that step, we'll need to add a new `module-where-newline` config option (false by default, to keep behavior with Fourmolu's default of diff-friendly exports). @Bodigrim feel free to make a PR

**Comment by georgefst** [comment]
> false by default, to keep behavior with Fourmolu's default of diff-friendly exports

As I see it, neither option is actually more diff-friendly than the other. I think there's an argument for making it input-dependent by default, as we recently did with `auto` in #229 (in hindsight, I wonder if we should have involved the `--respectful` flag there, which was meant for such behaviour).

**Comment by Bodigrim** [comment]
OK, we have an answer upstream. I think it would be nice to make this input-dependent, maybe even covered by `respectful` flag?.. Sorry, I'm not up to preparing a PR myself anytime soon, this is a very new codebase for me.

**Comment by brandonchinn178** [comment]
I think respecting (ha) `respectful` here makes sense, for both diff-friendly = true/false.

Neither @georgefst nor I have been actively working on this much lately. A PR from someone would be greatly appreciated. The relevant lines are probably:

https://github.com/fourmolu/fourmolu/blob/c6d7156b5f3e8287960a76e777c40b62ebfdbcb3/src/Ormolu/Printer/Meat/Module.hs#L57-L68

**Comment by brandonchinn178** [comment]
After https://github.com/fourmolu/fourmolu/pull/244, should just require adding a line here with something to do with `poRespectful` and `didUserAddNewline`

https://github.com/fourmolu/fourmolu/blob/d8f22852506644238e885695a2dc61f4d4da19f4/src/Ormolu/Printer/Meat/Module.hs#L73-L76

**Comment by brandonchinn178** [comment]
https://github.com/fourmolu/fourmolu/pull/245/files#diff-e52c25adcba086363cf917b99cbcd1a15a103063f708dac25310b2c435c08854

@tysonzero @Bodigrim is this output the desired behavior?

**Comment by Bodigrim** [comment]
LGTM!

**Comment by Bodigrim** [comment]
Thanks @brandonchinn178!
