### ISSUE TITLE
AST differences with consecutive newlines in haddock

### ISSUE THREAD

**Issue by tchoutri** [fourmolu/fourmolu#172]
I'm getting this message when running 0.6.0.0 on my code:

```
❯ fourmolu --mode inplace src/Database/PostgreSQL/Entity.hs
Loaded config from: ~/Projects/pg-entity/fourmolu.yaml
src/Database/PostgreSQL/Entity.hs
  AST of input and AST of formatted code differ.
    at src/Database/PostgreSQL/Entity.hs:(3,1)-(15,2)
  Please, consider reporting the bug.
```

The file in question is: https://github.com/tchoutri/pg-entity/blob/main/src/Database/PostgreSQL/Entity.hs.

**Comment by brandonchinn178** [comment]
Thanks! Can you run with --unsafe? What does the diff look like? That should solve the immediate issue, but I'll take a look to see if theres anything on our end to fix it

**Comment by brandonchinn178** [comment]
Ok the issue is the double newline in the module comment. Removing the extra newline works

**Comment by tchoutri** [comment]
Ok thanks :) 
Might be worth outputting some kind of diff for those cases ;-)

**Comment by brandonchinn178** [comment]
Yeah, maybe!
