### ISSUE TITLE
fourmolu GitHub Action

### ISSUE THREAD

**Issue by cdepillabout** [fourmolu/fourmolu#188]
We created a fourmolu GitHub Action to use in our codebase at work: https://github.com/bitnomial/fourmolu-action.  This is basically a straight port of the ormolu GitHub Action from Mark: https://github.com/mrkkrp/ormolu-action.

Would there be any interest in moving this under the [fourmolu GitHub organization](https://github.com/fourmolu) to a repo like https://github.com/fourmolu/fourmolu-action?  I'm imagining that myself and one or two other people from [Bitnomial](https://github.com/bitnomial) would be given Write access (so that we can merge PRs and make releases), but ultimate control over the repo would be with the fourmolu org.

The advantages of doing this:

- One single "blessed" fourmolu Action.  It would be more likely to get PRs implementing new features, rather than people forking or creating their own.
- We can distribute some of the maintenance burden.  I'm imaging that myself (or other people from Bitnomial) will do most of the maintenance/releases, but if we ever don't make a timely release, other people from the fourmolu org could step in.

The disadvantages:

- It is possible that we stop using fourmolu at Bitnomial at some point in the future.  At that point we would likely stop spending time keeping the repo up-to-date.  `fourmolu` users might expect the fourmolu Action to always be up-to-date, but the other fourmolu maintainers might not have time for this.  (In practice I imagine it is unlikely we would stop using fourmolu, at least anytime soon, but you never know what the future holds.)

If this sounds like a good idea, let me know and I can try to figure out how to do a repo transfer across organizations.

**Comment by brandonchinn178** [comment]
Sounds good to me! @georgefst?

**Comment by wraithm** [comment]
@brandonchinn178 Thanks for making releases of fourmolu on the github page. That made this easy!

**Comment by georgefst** [comment]
> Sounds good to me! @georgefst?

Yep, sounds good!

**Comment by cdepillabout** [comment]
@brandonchinn178 @georgefst Thanks!

I imagine the following steps will need to happen:

1. Could either @georgefst or @brandonchinn178 create an empty repo like https://github.com/fourmolu/fourmolu-action?  (I'd specifically like this to be a blank repo, instead of a fork of https://github.com/bitnomial/fourmolu-action, so that GitHub's UI doesn't mess anyone up when they try to send PRs.)
2. And then give myself and @wraithm write/maintainer/admin access to this repo.  I imagine write access will be sufficient, but admin/maintainer access might be necessary for something.  Although I could always just ask for help if I don't have necessary permissions.
3. I'll push the contents of https://github.com/bitnomial/fourmolu-action to the new empty https://github.com/fourmolu/fourmolu-action repo.
4. I'll deprecate/archive https://github.com/bitnomial/fourmolu-action.
5. I'll make a first release on https://github.com/fourmolu/fourmolu-action.
6. Maybe make an announcement post to reddit?

**Comment by brandonchinn178** [comment]
Ok done! https://github.com/fourmolu/fourmolu-action

**Comment by brandonchinn178** [comment]
Done, does that work for you?

**Comment by cdepillabout** [comment]
Thanks, I was able to make an initial release!

https://github.com/marketplace/actions/run-fourmolu

Moving forward, I'll have to keep watch over the https://github.com/fourmolu/fourmolu repo, and create a new release of https://github.com/fourmolu/fourmolu-action whenever there is a new version of `fourmolu`.  Please feel free to open an issue on https://github.com/fourmolu/fourmolu-action if I ever miss a fourmolu release.
