### ISSUE TITLE
Consolidate import-export-comma-style and diff-friendly-import-export

### ISSUE THREAD

**Issue by brandonchinn178** [fourmolu/fourmolu#201]
https://github.com/fourmolu/fourmolu/pull/108#issuecomment-1100916957
https://github.com/fourmolu/fourmolu/pull/169#issuecomment-1141459894

These two options aren't completely independent; `import-export-comma-style=Leading` and `diff-friendly-import-export=True` is probably not a format anyone wants. We might want to instead have a single configuration option `import-export-style: leading, trailing, diff-friendly`

**Comment by 3kyro** [comment]
I'm in favor of the single configuration despite the breakage. We could also provide automatic modification of config files with a deprecation notice that will be kept for a couple of versions.

**Comment by brandonchinn178** [comment]
I would weakly prefer not doing any automatic modification of config files; seems like unnecessary complexity. But yes, that all sounds good

**Comment by 3kyro** [comment]
great, I'll work on it in the next days.

**Comment by georgefst** [comment]
Closed by #207.

Although I would quite like to see a shell script or something (cabal script?) that could be used to migrate config files. This would set a good precedent.
