### ISSUE TITLE
Configuration for styling let

### ISSUE THREAD

**Issue by brandonchinn178** [fourmolu/fourmolu#202]
**Describe the option you'd like to add**
* name: `let-style`
    * `inline`: first definition is on the same line as `let`; subsequent definitions are aligned to this definition. If there's an `in` clause, `in` is aligned with start of `let` column, `in` contents is aligned with `let` definitions (i.e. 2 spaces after `in`)
    * `inline-ormolu`: Same as `inline`, except if there's an `in` clause, `in` is aligned with end of `let` column (i.e. 1 space before and after `in`)
    * `auto-newline`: `inline` when there's only one `let` binding, otherwise `newline`
    * `newline`: first definition is on the line after `let`, indented once, with subsequent definitions aligned to this definition. If there's an `in` clause, `in` is aligned with start of `let` column, and the `in` contents start on the next line, indented once
* Ormolu configured with `inline-ormolu`
* I think default behavior should be `auto-newline`, but open to suggestions.

**Show a code example exemplifying the different option settings**
```hs
-- inline
-- note that the space before the `in` is moved to after, not just removed
let a = 1
    b = 2
in  a + b

-- inline-ormolu
let a = 1
    b = 2
 in a + b

-- auto-newline (indent=2)
let a = 1
in  a + 2

-- newline (indent=2)
let
  a = 1
in
  a + 2

-- auto-newline + newline (indent=2)
let
  a = 1
  b = 2
in
  a + b

-- auto-newline + newline (indent=4)
let
    a = 1
    b = 2
in
    a + b
```
Notes:
* With `newline`, we won't support aligning `in` with the end of `let`; it just doesn't really look good. Originally, I wrote this issue where there were multiple independent toggles, but pretty much nothing else looked good. Happy to hear other suggestions as well.
* If someone adds the `in` clause in a do-block, we'll change `"in "` to `" in"` for everything, since keeping it on the same level as `let` is invalid `do`-syntax

**Comment by dpwiz** [comment]
Does it affect formatting `let` insdide `do` blocks?

**Comment by brandonchinn178** [comment]
Good question. I'd say yes; I can't imagine anyone choosing one of these values for let-in but and a different one for do-let.

**Comment by dpwiz** [comment]
Oneliner `lets` are ok inside `do` blocks:

```haskell
main = do
  let x = not $ complex enough

  let
    y = 1
    z = "too many"

  let
    that's = case 9000 of
      _ ->
        too "much"

  pure ()
```

**Comment by dpwiz** [comment]
`auto-newline` + `newline` + `inline` when it is a single-line statement in a group inside `do`.

**Comment by dpwiz** [comment]
I'd imagine I would use `auto-newline` + `newline` for let/in pairs and something like "conditional" `inline` in do blocks.

Perhaps `do` blocks should have their newline programmable - do not format if it is a single line, or format to the general `let` settings.

**Comment by brandonchinn178** [comment]
> do not format if it is a single line

Isn't that auto-newline? Or do you mean that if there are two defs in a single let binding, let-in should be newline but do should be inline?

```hs
let
  a = 1
  b = 2
in
  a + b

do
  let a = 1
      b = 2
  return $ a + b
```
Why would you want those different?

**Comment by dpwiz** [comment]
> Isn't that auto-newline?

It may be. That's what I'm trying to understand :sweat_smile:

**Comment by brandonchinn178** [comment]
ah sorry for the miscommunication 😞. You're right, I should've explained the options in plaintext. I've updated the PR body, does that help?

**Comment by dpwiz** [comment]
Yes, `auto-newline` it is.

What's missing is interaction with case, if/then/else and inner lets.
