### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by parsonsmatt** [fourmolu/fourmolu#205]
I've just upgraded the work codebase to 0.7.0.1 and have noticed a pretty massive performance regression. Running `fourmolu` over the entire codebase took 50s with 0.3.0.0 and now takes 25 minutes. I'm going to do more testing and validation on this issue but it's getting late on a Friday

**Comment by brandonchinn178** [comment]
That's odd, it runs in 30s for my company codebase. Can you also see if Ormolu has the same issue?

**Comment by georgefst** [comment]
> Can you also see if Ormolu has the same issue?

Yes, that's where I'd start. Most of the execution time is spent parsing, so I'd expect (and _hope_!) this is an upstream issue in `ormolu`, `ghc-lib-parser`, or `ghc`.

**Comment by parsonsmatt** [comment]
At the very least, it should be easy to [add multithreading](https://github.com/tweag/ormolu/pull/896). A 4-8x speedup wouldn't be fast enough for us, but hey, free speed!

**Comment by parsonsmatt** [comment]
Turning on `fixity-th` did not meaningfully effect execution time (19:00 vs 18:45) on the codebase. Currently trying with `ormolu`, and it looks to be similarly slow.

**Comment by georgefst** [comment]
> That's odd, it runs in 30s for my company codebase. Can you also see if Ormolu has the same issue?

How long did it take with 0.6?

**Comment by brandonchinn178** [comment]
@georgefst 0.6 took 35s just now

**Comment by parsonsmatt** [comment]
Upstream issue: https://github.com/tweag/ormolu/issues/897

**Comment by brandonchinn178** [comment]
Seems to be fixed upstream, which is merged into fourmolu 0.8.0.0
