### ISSUE TITLE
CLI: Support specifying input folders in addition to just input files

### ISSUE THREAD

**Issue by matobet** [fourmolu/fourmolu#213]
It would be nice if fourmolu could take folders as well as files as an input and would process all haskell files in that folder (recursively)
so instead of 
```
fourmolu -i $(find src -name '*.hs')
```
I'd be able to do just 
```
fourmolu -i src
```
This is consistent what formatters in other languages support and would be a nice quality of life improvement.

**Comment by brandonchinn178** [comment]
I believe this is an Ormolu issue, not specific to Fourmolu. Could you create an issue there instead?

**Comment by matobet** [comment]
Ok wasn't sure what is the proper place to report this, will do that :+1:

**Comment by matobet** [comment]
Created https://github.com/tweag/ormolu/issues/910

**Comment by georgefst** [comment]
This was rejected upstream in https://github.com/tweag/ormolu/pull/697, seeing as:

> there are too many subtle details about walking directories [that] do not belong in Ormolu

I'm not overly concerned about that, and suggest that we just pick an off-the-shelf solution e.g. [`dir-traverse`](https://hackage.haskell.org/package/dir-traverse-0.2.3.0/docs/System-Directory-Recursive.html#v:getDirRecursive). Other formatters, linters and similar tools usually provide this option in my experience, and there are all sorts of reasons not to want to rely on shell scripts.

So would you be willing to port https://github.com/tweag/ormolu/pull/911 to Fourmolu?

**Comment by brandonchinn178** [comment]
Agreed; that being said, it's not difficult writing a recursive walk with directory's listDirectory (or if we're already using path, path-io's listDirRecur) I would prefer to avoid adding an extra dependency just for a simple loop

**Comment by matobet** [comment]
@georgefst with regards to porting, I originally implemented https://github.com/matobet/fourmolu/commit/1565d64f6b77b681da49f368c0a6018e0e9c57df and only after @brandonchinn178 's comment I _ported_ it to ormolu where it was rejected :-) 
So if you like we can just directly take that original implementation (which I also tested) or if there is general opposition to adding dependencies I can definitely have a look at walking the directories manually. Although in general I'm a fan of not reinventing the wheel when a minimal library exists for the job :-)

**Comment by brandonchinn178** [comment]
I'm only weakly against adding `dir-traverse` in this case. In general, I agree adding a dependency is better than reinventing the wheel, but in this case, it's only reinventing like 8 lines:
```hs
listDirectoryRecursive :: FilePath -> IO [FilePath]
listDirectoryRecursive fp = fmap concat . mapM (go . (fp </>)) =<< listDirectory fp
  where
    go child = do
      isDir <- doesDirectoryExist child
      if isDir
        then listDirectoryRecursive child
        else pure [child]
```

**Comment by matobet** [comment]
@brandonchinn178 indeed, the 8 lines did the trick! Here's a version that adds no new dependencies: https://github.com/fourmolu/fourmolu/pull/214

**Comment by georgefst** [comment]
> I think we all agree we wouldn't want a `leftpad`-like library

Not totally. Some of the risks to having dependencies in NPM don't apply to Hackage.

Anyway, I'm weakly in favour of using the dependency, but I won't let that hold up a PR. Admittedly, I did assume that the library was doing something slightly more complex e.g. with symlink handling.
