### ISSUE TITLE
Command-line options do not override options in a configuration file!

### ISSUE THREAD

**Issue by kindaro** [fourmolu/fourmolu#224]
> Command-line options override options in a configuration file. Run `fourmolu --help` to see all options.

— `README.md`

## See for yourself:

```
% cabal run fourmolu -- --indentation 4 --newlines-between-decls 2 src/Ormolu.hs
% rm `fourmolu.yaml`
% cabal run fourmolu -- --indentation 4 --newlines-between-decls 2 src/Ormolu.hs
```

### Expected:

In either invocation, there is indentation by 4 spaces and 2 blank lines between top level declarations.

### Actual:

In the first invocation, there is indentation by 2 spaces and 1 blank line between top level declarations, as written in `fourmolu.yaml` — the options set in `fourmolu.yaml` override command line options, contrary to the documentation.

**Comment by brandonchinn178** [comment]
I can repro it too! I'll add a test suite and investigate what's going on

**Comment by brandonchinn178** [comment]
Wow totally broke this back in 0.7.0.0: https://github.com/fourmolu/fourmolu/pull/150

Specifically these lines:
https://github.com/fourmolu/fourmolu/pull/150/files#diff-d3e498a88b4c374b1edbd8693542a73e944d51a24a64a683658926ba655bc6ffR111-R113

Currently, the options resolve as `config file <> cli options <> default`, but it should be `cli options <> config file <> default`. Putting up a PR shortly

**Comment by kindaro** [comment]
Fantastic, thank you!
