### ISSUE TITLE
Test suite `tests` fails when running with `cabal run`.

### ISSUE THREAD

**Issue by kindaro** [fourmolu/fourmolu#231]
This is not a big deal in principle, since I can still run `cabal test`, but it is more comfortable to run `cabal run test:tests` because of beautiful colourful output and the availability of command line options to the test suite.

## See for yourself:

```
% cabal run test:tests -- --match "/Ormolu.Config.Options/Fourmolu configuration via CLI/CLI options override config file option/"
Build profile: -w ghc-9.2.2 -O1
In order, the following will be built (use -v for more details):
 - fourmolu-0.8.1.0 (test:tests) (additional components to build)
Preprocessing test suite 'tests' for fourmolu-0.8.1.0..
Building test suite 'tests' for fourmolu-0.8.1.0..

Ormolu.Config.Options
  Fourmolu configuration via CLI
    CLI options override config file option [✘]

Failures:

  tests/Ormolu/Config/OptionsSpec.hs:46:17: 
  1) Ormolu.Config.Options, Fourmolu configuration via CLI, CLI options override config file option
       expected: main :: IO ()
                 main =
                     print 10
                 
        but got: main :: IO ()
                 main =
                   print 10
                 

  To rerun use: --match "/Ormolu.Config.Options/Fourmolu configuration via CLI/CLI options override config file option/"

Randomized with seed 1662498047

Finished in 0.0242 seconds
1 example, 1 failure
```

### Expected:

If the the test suite passes when running with `cabal test`, every single test case should pass when run with `cabal run test:tests -- --match …`.

### Actual:

The test suite passes when running with `cabal test`, but one test case fails when running `cabal run test:tests`.

**Comment by brandonchinn178** [comment]
Yeah, this is the same as #215; cabal doesnt automatically put the built executable on PATH. We have other test suites that do this too: fixity and region tests. Those probably pass because you have a global fourmolu installed. If you have a global fourmolu installed, you can upgrade it and this test should pass too.

I'll need to think about how to keep these tests passing on cabal

**Comment by brandonchinn178** [comment]
My initial thought is this is a cabal issue, because we set `build-tool-depends`, which should guarantee the executable is on PATH. Cabal does say that that only works for nix-style local builds, which `cabal run` might not do. Maybe make a Cabal issue?

**Comment by kindaro** [comment]
I made some issue to Cabal haskell/cabal#8391. Not sure if it says what you @brandonchinn178 expected it to be saying so I invite you to offer corrections in there or open another issue as you see fit.

**Comment by kindaro** [comment]
Alright, it seems the issue to Cabal will simmer for a long time. For now, a blend of `cabal build`, `cabal exec` and `cabal list-bin` can give a good outcome:

```shell
grep 'test-suite' fourmolu.cabal |
    cut -d ' ' -f 2 |
    while read name
    do
        cabal build "test:$name"
        cabal exec `cabal list-bin test:"$name"`
    done
```

**Comment by brandonchinn178** [comment]
Related: https://github.com/fourmolu/fourmolu/pull/236

**Comment by expipiplus1** [comment]
One can observe similar behavior with the `test` command to the program described by `Setup.hs`

**Comment by kindaro** [comment]
The issue to Cabal may have been fixed, see https://github.com/haskell/cabal/issues/8391 and https://github.com/haskell/cabal/pull/9527. Pinging @brandonchinn178 — please be informed.

**Comment by georgefst** [comment]
This does seems to be fixed: `cabal run test:tests -- -m 'CLI options override default'` works, without any `fourmolu` on my `PATH`.
