### ISSUE TITLE
Add 'only-args' option to 'function-arrows'

### ISSUE THREAD

**Issue by brandonchinn178** [fourmolu/fourmolu#233]
**Describe the option you'd like to add**
#209 added support for leading arrows, but one thing people might prefer is a mixture of leading/trailing, where only the thin arrows are leading. Why?

* `::` is next to function name, for greppability
* Can use trailing haddocks for arguments
* Friendlier diffs when adding explicit `forall` or constraints

**Show a code example exemplifying the different option settings**
```hs
-- trailing
foo ::
  forall a.
  (C1, C2) =>
  Int ->
  String ->
  Bool

-- leading
foo
  :: forall a
  . (C1, C2)
  => Int
  -> String
  -> Bool

-- only-args
foo ::
  forall a.
  (C1, C2) =>
     Int
  -> String
  -> Bool
```

**Comment by tchoutri** [comment]
I would definitely support an option to keep the `::` on the same line as the function name and having aligned leading arrows. Especially for those of us who can't use HLS yet and don't necessarily have a tags program installed.

**Comment by brandonchinn178** [comment]
Is there a reason why you want everything aligned after the function name? The problem with that is the bad diffs when renaming the function. IMO it also doesnt look great to have signatures misaligned across a file

```hs
someLongFuncName :: Int
                 -> String
                 -> Bool

anotherFunc :: Int
            -> String
            -> Bool
```
