### ISSUE TITLE
Hackage CI build failing

### ISSUE THREAD

**Issue by georgefst** [fourmolu/fourmolu#240]
https://hackage.haskell.org/package/fourmolu-0.8.2.0/reports/2

Ormolu has the same problem. I tried to trigger a rebuild over two weeks ago, but there's no sign of it.

Even from the log, I don't quite understand why this is happening. But this is presumably not our fault. Maybe we've just got to wait for Hackage to upgrade to GHC 9.2?

@brandonchinn178 I'm guessing you manually uploaded the documentation? If so, thanks!

**Comment by brandonchinn178** [comment]
https://github.com/haskell/hackage-server/issues/1132

It should be resolved next release

**Comment by brandonchinn178** [comment]
Seems to be fixed now!
