### ISSUE TITLE
Module level comments starting with `>` lead to problems when using `--haddock-style=single-line`

### ISSUE THREAD

**Issue by joncol** [fourmolu/fourmolu#253]
**Is your bug specific to Fourmolu?**
- [x] Yes, I've verified that Ormolu does not have this bug

**Describe the bug**

Example:
```haskell
{- | Dummy
> Foo
-}
module Dummy () where
```

Using `fourmolu -i --haddock-style=single-line` on the above, yields:
```haskell
-- | Dummy
--> Foo
module Dummy () where
```
which does not compile. The case seems to be the same also for other "special" characters.

**Comment by brandonchinn178** [comment]
Duplicate: #212
