### ISSUE TITLE
`let-style: auto` leads to reformatting

### ISSUE THREAD

**Issue by ocharles** [fourmolu/fourmolu#256]
**Is your bug specific to Fourmolu?**
- [X] Yes, I've verified that Ormolu does not have this bug

**Describe the bug**
0.9 adds the new `let-style` option, and the changelog writes:

> The default is set to let-style: auto and in-style: right-align, which should not reformat already formatted files

However, I'm seeing:

```diff
-          let v = V2 0 0 in Hedgehog.diff (transform32 t1 v) closeEnough (transform32 t2 v)
-          let v = V2 1 0 in Hedgehog.diff (transform32 t1 v) closeEnough (transform32 t2 v)
-          let v = V2 0 1 in Hedgehog.diff (transform32 t1 v) closeEnough (transform32 t2 v)
-          let v = V2 1 1 in Hedgehog.diff (transform32 t1 v) closeEnough (transform32 t2 v)
+          let v = V2 0 0
+           in Hedgehog.diff (transform32 t1 v) closeEnough (transform32 t2 v)
+          let v = V2 1 0
+           in Hedgehog.diff (transform32 t1 v) closeEnough (transform32 t2 v)
+          let v = V2 0 1
+           in Hedgehog.diff (transform32 t1 v) closeEnough (transform32 t2 v)
+          let v = V2 1 1
+           in Hedgehog.diff (transform32 t1 v) closeEnough (transform32 t2 v)
```

This isn't the end of the world, but I thought I'd raise it! This isn't the only occurrence, another is:

```diff
-        let -- This method also fills in any holes in the names (i.e. if "CC2" exists and "CC4" exists, but "CC3" does not, it will be generated)
-            stripPrefixAlpha :: Text -> Maybe Word
-            stripPrefixAlpha match =
-              case T.decimal
-                ( fromJustNote
-                    "expandNumeric"
-                    (T.stripPrefix name match)
-                ) of
-                Left _ -> Nothing
-                Right (w, _) -> Just w
-
-            expansions :: [Word]
-            expansions = sort $ mapMaybe stripPrefixAlpha names :: [Word]
-
-            expansion :: Word
-            expansion =
-              maybe 1 succ . lastMay . fst . spanSeq ((>=) . succ) $
-                expansions
-         in name ++ tshow expansion ++ suffix
+        let
+          -- This method also fills in any holes in the names (i.e. if "CC2" exists and "CC4" exists, but "CC3" does not, it will be generated)
+          stripPrefixAlpha :: Text -> Maybe Word
+          stripPrefixAlpha match =
+            case T.decimal
+              ( fromJustNote
+                  "expandNumeric"
+                  (T.stripPrefix name match)
+              ) of
+              Left _ -> Nothing
+              Right (w, _) -> Just w
+
+          expansions :: [Word]
+          expansions = sort $ mapMaybe stripPrefixAlpha names :: [Word]
+
+          expansion :: Word
+          expansion =
+            maybe 1 succ . lastMay . fst . spanSeq ((>=) . succ) $
+              expansions
+         in
+          name ++ tshow expansion ++ suffix
```

My `fourmolu.yaml` is:

```yaml
indentation: 2
comma-style: leading
import-export-style: diff-friendly
indent-wheres: true
record-brace-space: false
respectful: true
haddock-style: multi-line
newlines-between-decls: 2
fixities: []
```

**Comment by brandonchinn178** [comment]
ah darn it. So the first one is definitely unintentional, I'll make that fix. The second one is what I _would_ expect from `auto`, but I didn't realize it would break existing formatted code. So I'll just change the default to be `inline`

**Comment by georgefst** [comment]
> The second one is what I _would_ expect from `auto`, but I didn't realize it would break existing formatted code. So I'll just change the default to be `inline`

I haven't personally got time _right_ now, but I would like to think about this before we commit to reverting that change. I'd hope we can find some sort of compromise.

**Comment by brandonchinn178** [comment]
What's your hesitation in reverting the change (the change here being "making the default auto instead of inline")? Do you feel strongly that `auto` should be the default?

**Comment by brandonchinn178** [comment]
@georgefst can you give your quick thoughts on this? With the Ormolu release today, I'm hoping to make a new release soon to get GHC 9.4 support, and it'd be great to resolve this one way or another

**Comment by georgefst** [comment]
> @georgefst can you give your quick thoughts on this?

Will do by the weekend. I need to run some experiments.

**Comment by georgefst** [comment]
> Edit: alternatively, we could just keep auto and reword the changelog to say "most formatted code should not be reformatted, with some exceptions"

I think this is what we should do, though I'd specifically mention that it involves unusual comma placement. It's enough of an edge case that I'm not really bothered. I'd personally always put the comment above the `let` itself, which is still always fine.

> Do you feel strongly that auto should be the default?

As a general point, yes. I think Ormolu/Fourmolu's strongest feature compared to a lot of other formatters I've used (Haskell and otherwise) is the ability for the user to keep some control over how they'd like things formatted, on an ad-hoc basis.
