### ISSUE TITLE
Pargmas in haddock codeblocks are wrongfully escaped

### ISSUE THREAD

**Issue by lehins** [fourmolu/fourmolu#265]
**Is your bug specific to Fourmolu?**
- [x] Yes, I've verified that Ormolu does not have this bug

**Describe the bug**
Provide steps to reproduce the bug, and what the expected behavior should be.

Here is totally valid haddock that needs no escaping or modification:

```haskell
-- | Haddock with bird track
--
-- > bar :: Bar ()
-- > bar = ()
-- > {-# INLINE bar #-}
--
-- and with regular codeblock
--
-- @
-- bar :: Bar ()
-- bar = ()
-- {-# INLINE bar #-}
-- @
--
-- Outside of codeblock
--
-- {-# INLINE bar #-}
--
-- Multi-line syntax inside single-line haddock (both in codeblock and outside)
--
-- {- -}
--
-- > {- -}
foo :: ()
foo = ()
```

Here is the output when `haddock-2.26` is applied to this code:
 
![image](https://user-images.githubusercontent.com/2333894/204107910-7349d184-711e-4ec0-adf6-9e6fbd8d0944.png)

However fourmolu will escape all occurrences of `{-` ans `-}` regardless of the `--haddock-style` setting. 

```shell
$ fourmolu PragmaInHaddock.hs --haddock-style single-line -m inplace
```

Here is the diff of applying this command ([as a commit on github](https://github.com/lehins/bugs/commit/d16bfadf045664915a16f98f8cd58d1da9d5598d))

```diff
@@ -4,24 +4,24 @@ module PragmaInHaddock where
 --
 -- > bar :: Bar ()
 -- > bar = ()
--- > {-# INLINE bar #-}
+-- > {\-# INLINE bar #-\}
 --
 -- and with regular codeblock
 --
 -- @
 -- bar :: Bar ()
 -- bar = ()
--- {-# INLINE bar #-}
+-- {\-# INLINE bar #-\}
 -- @
 --
 -- Outside of codeblock
 --
--- {-# INLINE bar #-}
+-- {\-# INLINE bar #-\}
 --
 -- Multi-line syntax inside single-line haddock (both in codeblock and outside)
 --
--- {- -}
+-- {\- -\}
 --
--- > {- -}
+-- > {\- -\}
 foo :: ()
 foo = ()
```

Despite that this escaping is wrong and unnecessary, most of it does not hurt the produced haddock output, except the code block in bird track style. Here is the generated haddock after fourmolu:

![image](https://user-images.githubusercontent.com/2333894/204108114-7bbe8ed0-cff5-46cd-b5d9-f6fe4661afbf.png)

As you can see only these were affected:
```haskell
{\-# INLINE bar #-\}
```
and
```haskell
{\- -\}
```

**Comment by lehins** [comment]
I think the most sens would make is to not do any escaping when `single-line` mode is being used, since there is never a case when it is needed.

**Comment by brandonchinn178** [comment]
Makes sense to me! @georgefst do you have any more context on this?

**Comment by georgefst** [comment]
Yep, this is definitely a bug, and probably my fault for not considering all edge cases when implementing `multi-line` mode.

> I think the most sense would make is to not do any escaping when `single-line` mode is being used, since there is never a case when escaping is needed.

This sounds like the right fix.
