### ISSUE TITLE
Export parse error when `leading` import export setting

### ISSUE THREAD

**Issue by lehins** [fourmolu/fourmolu#267]
**Is your bug specific to Fourmolu?**
- [x] Yes, I've verified that Ormolu does not have this bug

Adding a `-- * Foo` trips up the parser when `--import-export-style leading` is used.

Here is a minimal reproduction.

```haskell
module Foo
  ( -- * Foo
    foo
  ) where

foo :: ()
foo = ()
```

The actual failure:

```shell
> fourmolu test-parse.hs --import-export-style leading
Could not find a .cabal file for test-parse.hs
test-parse.hs:3:7-9
  Parsing of formatted code failed:  parse error on input `foo'
```

**Comment by georgefst** [comment]
This is the current output (you can see this by passing `--unsafe`):

```hs
module Foo
    ( -- * Foo
    , foo
    )
where
```

Presumably (without modifying GHC's parser to be more liberal), we want this, as it's similar to what we'd get if there were a second item in the list:

```hs
module Foo
    ( -- * Foo
      foo
    )
where
```

Personally, I think this is really ugly and see it as another reason to use trailing commas in export lists, so I'll leave this up to someone who uses the option.

**Comment by lehins** [comment]
I personally like the `diff-friendly` option. But, I accidentally discovered this bug, so decided to report it. Considering that this is totally valid Haskell, IMHO `fourmolu` shouldn't choke on it.

**Comment by georgefst** [comment]
Oh I totally agree, and thanks for opening the bug report! All I meant was that I'm not our only maintainer, I'm not the one who implemented the option, and I'm not certain what output is desirable, so it's likely that someone else is better placed to fix this.

**Comment by jonathanknowles** [comment]
We can also reproduce this parsing error on the following file: [NonRandom.hs](https://github.com/input-output-hk/cardano-wallet/blob/74181283b27a681fffbd3ca0add6a43ff20d61f2/lib/primitive/lib/Control/Monad/Random/NonRandom.hs#L12).

The parsing error _doesn't_ appear with `ormolu`. We're using these versions and fourmolu configuration:
```
$ ormolu --version
ormolu 0.5.0.1 UNKNOWN UNKNOWN
using ghc-lib-parser 9.2.5.20221107

$ fourmolu --version
fourmolu 0.9.0.0 UNKNOWN UNKNOWN
using ghc-lib-parser 9.2.5.20221107
```
```yaml
comma-style: leading
function-arrows: leading
import-export-style: leading
fixities: []
haddock-style: single-line
indent-wheres: true
indentation: 4
let-style: newline
in-style: left-align
newlines-between-decls: 1
record-brace-space: true
respectful: false
```

Before:
```hs
module Control.Monad.Random.NonRandom
    (
    -- * Non-random contexts
      NonRandom (..)
    ) where
```
Running `fourmolu` in safe mode produces the following error:
```
$ fourmolu --mode inplace lib/primitive/lib/Control/Monad/Random/NonRandom.hs
lib/primitive/lib/Control/Monad/Random/NonRandom.hs:13:5-13
  Parsing of formatted code failed:  parse error on input `NonRandom'
```
Running `fourmolu` with `--unsafe` produces the following diff:
```diff
-    (
-    -- * Non-random contexts
-      NonRandom (..)
-
-    ) where
+    ( -- * Non-random contexts
+    , NonRandom (..)
+    )
+where
```

**Comment by brandonchinn178** [comment]
I think this is fixed with https://github.com/fourmolu/fourmolu/issues/341. This is what I get with current Fourmolu:
```hs
module Control.Monad.Random.NonRandom
  ( -- * Non-random contexts
    NonRandom (..),
  )
where
```
