### ISSUE TITLE
Add "Fourmolu Live"

### ISSUE THREAD

**Issue by brandonchinn178** [fourmolu/fourmolu#282]
I really like https://ormolu-live.tweag.io/ because it allows me to try out Ormolu formatting without downloading it. Since it's (presumably) deployed after every push, it also represents the most up-to-date formatting, so users could quickly try it before writing issues, mitigating "this was fixed in the recent version, are you using the latest version" situations. (e.g. #279)

General steps needed:
1. Add `ormolu-live` (renamed to `fourmolu-live`) to `stack.yaml` + `cabal.project`
2. Delete `deploy.sh` and `shell.nix` (and update `DEVELOPER.md` instructions for merging upstream)
3. Make a new `fourmolu.github.io` repo that will host the page with [GitHub pages](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites)
4. Write GitHub actions workflow to build `fourmolu-live` every PR, and, on `main`, push new static files to the `fourmolu.github.io` repo
5. Point repo website to `https://fourmolu.github.io`

Future work:
1. Add configuration section to the page
2. Add docs under `https://fourmolu.github.io/config` that provides pages for each configuration option showing example
    * Generate with `config/Generate.hs`
    * Make sure each option indicates when it was added (new options should say `unreleased`)
    * Add link from main page to config docs
    * Replace configuration section in README with link
    * Update `DEVELOPER.md` + `pr-review-comment.yml` to include updating these docs
3. Update `DEVELOPER.md` to audit these docs every release
    * Replace all `unreleased` tags with new version tag

**Comment by georgefst** [comment]
Yep, this would be pretty cool.

For reference, I've done something similar before [for pretty-simple](https://cdepillabout.github.io/pretty-simple/), implemented in https://github.com/cdepillabout/pretty-simple/pull/116 (styling is still pretty rubbish - I'll get back to that some day...). Notably that has code for drop-downs for selecting enum options from a list, which Ormolu Live does not. In fact, while I'm not necessarily suggesting it's the right approach, it would probably be pretty easy to adapt the pretty-simple code for Fourmolu's purpose. I've thought about abstracting out a library for converting Haskell functions like `SomeSortOfOptionConstraint opts => opts -> Text -> Text` in to web apps.

**Comment by georgefst** [comment]
There is an argument for waiting until GHC's native JS backend has obsoleted GHCJS, so we don't have to faff about with Nix, but this could well take until GHC 9.8.

**Comment by brandonchinn178** [comment]
I can't seem to get GHCJS working anyway, so we might have to wait for native GHC support anyway :(

**Comment by georgefst** [comment]
With or without Nix? What I've picked up from various conversations is that the number of people currently using GHCJS without Nix is tiny, and may genuinely be zero.

**Comment by brandonchinn178** [comment]
Without Nix 😅 which I acknowledge is probably why. I just don't want to install Nix on my local machine. I can't even get the repo to build with `stack build` like the docs claim is possible 🕵️
