### ISSUE TITLE
Add `in-style` value to not align let body with patterns

### ISSUE THREAD

**Issue by tomsmeding** [fourmolu/fourmolu#291]
**Describe the option you'd like to add**
This would be an additional value for the `in-style` option; tentative name is `no-align` but this can be confusing with the currently existing values `left-align` and `right-align`, so suggestions welcome.

**Show a code example exemplifying the different option settings**
`in-style: left-align` (current result)
```hs
let Con a b = rhs1
    Con c d = rhs2
in  Con e f
```
`in-style: right-align` (current result)
```hs
let Con a b = rhs1
    Con c d = rhs2
 in Con e f
```
`in-style: no-align` (suggested new value)
```hs
let Con a b = rhs1
    Con c d = rhs2
in Con e f
```

**Motivation**
Short answer: I like my code this way. :)
<details><summary>Long answer: (click to expand, warning: subjective)</summary>
Both existing values align the let body with the patterns in its bindings, which makes no sense to me since the body (an expression) and the patterns are not even in the same syntactic category. Hence visual patterns, which alignment helps the human eye spot, will usually be deceptive instead of clarifying. This is especially true with large left-hand side patterns. Not adding additional spaces around `in` simultaneously solves this problem (by visually setting the body apart) and eliminates some spurious spaces that don't follow indentation levels.
</details>

**Implementation**
Because this would, as far as I can tell, be a very small change, I can implement this in a PR if you wish.

**Comment by georgefst** [comment]
> I can implement this in a PR if you wish.

Go for it!
