### ISSUE TITLE
The column-limit non-idempotence example is actually idempotent

### ISSUE THREAD

**Issue by expipiplus1** [fourmolu/fourmolu#321]
In the examples here the two latter examples are described as being different, however they are the same. 

https://github.com/fourmolu/fourmolu/blob/d6529770cda5c77fad5b3bc3f0a08f9b2eaedec9/data/fourmolu/column-limit/output-limit%3D80.hs#L111-L135

**Comment by brandonchinn178** [comment]
I think you're reading it wrong. Look at the input file; all three sections should be different. The fact that the first section is different from the other two in the output shows its not idempotent

**Comment by expipiplus1** [comment]
oh yikes, I was looking at the output file, not the input :woman_facepalming:
