### ISSUE TITLE
"Formatting is not idempotent" for `column-limit=30` in online example

### ISSUE THREAD

**Issue by uhbif19** [fourmolu/fourmolu#333]
**Is your bug specific to Fourmolu?**
- [x] Yes, I've verified that Ormolu does not have this bug

AFAIK, Ormolu does not have `column-limit` option.

**Did you try it on the web app?**
- [x] Yes, I've verified that https://fourmolu.github.io can reproduce this bug

**Describe the bug**

1. Go to `https://fourmolu.github.io/`
2. Set `column-limit` to 30
3. "Formatting is not idempotent. Please, consider reporting the bug."

**Comment by brandonchinn178** [comment]
Yes, this is expected. Please see the docs: https://fourmolu.github.io/config/column-limit/

**Comment by uhbif19** [comment]
If this is expected, could it not crash then?

**Comment by brandonchinn178** [comment]
`fourmolu` doesn't check idempotence by default; you have to pass `--check-idempotence` explicitly. In fourmolu.github.io, just uncheck "Check idempotence"

**Comment by uhbif19** [comment]
@brandonchinn178 

Thanks, I missed that.

Still I think changing "Please, consider reporting the bug." message in that case is worth to consider.
