### ISSUE TITLE
Find .cabal file from directory path not file, while using --stdin-input-file

### ISSUE THREAD

**Issue by 0rphee** [fourmolu/fourmolu#353]
(Please redirect me if needed to the ormolu repo)

In order to auto-format my files with my editor, `fourmolu` needs to support `stdin` input, which it does. Nevertheless, to correctly format from `stdin`, `fourmolu` needs to be run with the path to the file that is being fed through `stdin`: `fourmolu --stdin-input-file <PATH>/Main.hs`. However, unfortunately my [editor](https://github.com/helix-editor/helix) doesn't support any means to extract the name of the file to be formatted, and use it with the formatter at the moment (or for that matter, any other command). I tried passing the value of `$(pwd)` and though, `fourmolu` can find the `.cabal` file, because in that file it doesn't find the `directory` as a source file, it fails to account for GHC extensions when formatting from `stdin`.

Now, because `fourmolu` knows which extensions are on/off through the cabal info, I thought that perhaps, in cases where the name of the file cannot be given to `fourmolu` directly, it would be possible to parse the module name, and through it, find a matching source file name in the cabal info. (I understand that it may not be a reasonable option).

A less accurate way to "solve" this issue, could be, enable _all_ extensions mentioned anywhere in the `.cabal` file...

Here are some (maybe) relevant lines regarding the found .cabal file, but without a valid file name in it.
https://github.com/fourmolu/fourmolu/blob/47a40bb54f929bdd0fa1dd8d4ff4403bc4c26d72/app/Main.hs#L165C7-L174

Anyways, thank you in advance for any help!

**Comment by brandonchinn178** [comment]
Cool, I've been casually following development on helix! Looks like a cool editor.

Yeah, this doesn't seem specific to fourmolu. Can you make an issue in ormolu?

**Comment by 0rphee** [comment]
Ofc!

**Comment by brandonchinn178** [comment]
@0rphee can I close this with the resolution from the other issue?

**Comment by 0rphee** [comment]
oh yeah sure, i forgot about it, sorry
