### ISSUE TITLE
allow copying  configuration file from fourmolu.github.io

### ISSUE THREAD

**Issue by scarf005** [fourmolu/fourmolu#355]
![image](https://github.com/fourmolu/fourmolu/assets/54838975/1844967c-5237-4af0-b997-90f0993ae91f)

hi, it's great that we can freely test each configuration options, however it would be even better if there were an `Copy Configuration to Clipboard` button next to `Show internal parse result`. It could generate a `fourmolu.yaml` configuration and copy it into clipboard so it'd be easier to generate configuration file.

**Comment by brandonchinn178** [comment]
Great idea! I'll take a look

**Comment by brandonchinn178** [comment]
@scarf005 thanks for the idea!
