### ISSUE TITLE
Hangs on `--help` or `--no-such-option`.

### ISSUE THREAD

**Issue by kindaro** [fourmolu/fourmolu#359]
**Is your bug specific to Fourmolu?**
- [x] Yes, I've verified that Ormolu does not have this bug

**Did you try it on the web app?**
- [ ] ~~Yes, I've verified that https://fourmolu.github.io can reproduce this bug~~ — Not applicable.

**Describe the bug**

See this interactive session:

```
% cabal run fourmolu -- --version
Up to date
fourmolu 0.13.1.0
using ghc-lib-parser 9.6.2.20230523
% git rev-parse @
8aa2200fb38345d624d9682a051682094017bf8e
% cabal run fourmolu -- --help
Up to date
^C
% cabal run fourmolu -- --no-such-option
Up to date
Invalid option `--no-such-option'

Usage: fourmolu ^C
```

— Here, `^C` denotes me interrupting the program because it runs for what I deem to be too long. It keeps 1 core of my processor working for a long time without giving any output — this is wrong behaviour. I think it is trying to recursively compute something. It only needs to print a statically known string — no recursive computations should be needed.

**Comment by brandonchinn178** [comment]
Yeah, we've had this reported before: https://github.com/fourmolu/fourmolu/issues/328

Unfortunately, reinstalling fourmolu fixed both cases and I couldn't reproduce. How did you build fourmolu? What OS are you on?

**Comment by kindaro** [comment]
Linux.

**Comment by ocharles** [comment]
Could this be https://github.com/pcapriotti/optparse-applicative/issues/475?

**Comment by kindaro** [comment]
Yep. The version I was running was built with `optparse-applicative ==0.18.0.0`, after updating to `optparse-applicative ==0.18.1.0` everything works again.

**Comment by brandonchinn178** [comment]
@kindaro good to close?

**Comment by kindaro** [comment]
For me, the issue is solved.

I am not sure if some Cabal and Hackage magic should be put to work so that `optparse-applicative ==0.18.0.0` can never be picked as a dependency. I see it is already marked as deprecated on Hackage, but I do not know if marking a package version as deprecated bans it from Cabal's dependency resolution.

**Comment by ocharles** [comment]
I believe being deprecated is enough. Perhaps at the time you had an unfortunately timed Hackage database (from `cabal update`).

**Comment by kindaro** [comment]
I can still build a broken `fourmolu` if I say `cabal freeze` and then edit `cabal.project.freeze` so that it says `any.optparse-applicative ==0.18.0.0`. I tried and it hangs again. So it seems Cabal still treats this hanging version as valid. Out of abundance of caution, since this error is so severe, it would be better if it was impossible.

One possible solution is to ask the `optparse-applicative` people to add an unresolvable dependency to the broken version. I have seen this done somewhere some time.

**Comment by brandonchinn178** [comment]
I think there's some improvements that could be made around this problem, but it seems to be a Cabal/Hackage problem, not fourmolu. Perhaps we can close this ticket and open a new ticket in Cabal?

**Comment by kindaro** [comment]
I sent a message to the relevant issue in `optparse-applicative`. If they make the broken version unresolvable, the problem will be solved at the root.

**Comment by kindaro** [comment]
I think this is more or less handled. There is still an issue with Cabal <https://github.com/haskell/cabal/issues/9201>, but there is no sense in waiting for it to resolve.
