### ISSUE TITLE
Keep composition on a single line, as ormolu does

### ISSUE THREAD

**Issue by epoberezkin** [fourmolu/fourmolu#362]
# Problem

This code

```Haskell
f g h x y z =
  f . g . h $
    x
      y
      z
```

stays as is with ormolu, but is reformatted to below with fourmolu

```Haskell
f g h x y z =
  f
    . g
    . h
    $ x
      y
      z
```

which is much less readable, in general.

Not sure if this should simply change the default behaviour, or is somehow possible with the existing options, or requires a new option.

**Comment by epoberezkin** [comment]
Ok, it works as intended if fixities are added to this file: https://github.com/fourmolu/fourmolu/blob/main/fourmolu.yaml

```
fixities:
  - infixr 9  .
  - infixr 5  ++
  - infixl 4  <$
  - infixl 1  >>, >>=
  - infixr 1  =<<
  - infixr 0  $, $!
  - infixl 4 <*>, <*, *>, <**>
```

Not sure if they should be included in auto-generation.

**Comment by brandonchinn178** [comment]
Are you using the base prelude? If you're using your own prelude, you have to specify that your custom prelude reexports from base prelude.

If that's not the case, there's some other issue where fourmolu isnt detecting the fixity info correctly. Is the module mentioned in the cabal file? How are you invoking fourmolu?
