### ISSUE TITLE
Guards indentation

### ISSUE THREAD

**Issue by epoberezkin** [fourmolu/fourmolu#363]
**Describe the option you'd like to add**
* e.g. name of option, valid values, etc.
* What option setting would keep current behavior?

Proposed option: `indent-guards` with values `true` (current behaviour) and `false` (ormolu)

**Show a code example exemplifying the different option settings**

fourmolu (with `indentation: 2`):

```
f x y z
  | x =
      y
  | otherwise =
      z
```

ormolu (and fourmolu with `indent-guards: false`):

```Haskell
f x y z
  | x =
    y
  | otherwise =
    z
```

**Comment by epoberezkin** [comment]
In general, given that it is a fork, why the starting point wasn't taken to keep ormolu behaviour as default and add options (and, possibly, option sets) to change it?

**Comment by brandonchinn178** [comment]
Yes, I contributed that change to ormolu 🙂 It wasn't "for no apparent reason", I explain the reasoning in the issue.

Do you actually prefer it unindented, or do you just want to avoid reformatting your code? If the latter, you could just keep your fourmolu/ormolu version pinned, right? Or if you're concerned about git blame, you can add it to [`.git-blame-ignore-revs`](https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/)?

Regardless, feel free to submit a PR.

**Comment by brandonchinn178** [comment]
Personally, I would not want to set a precedent of adding a Fourmolu option to revert any change Ormolu makes. Fourmolu is committed to being very conservative about formatting changes (just like Ormolu, as Mark mentioned in the ormolu issue), so breaking changes should occur less and less frequently over time.

Plus, this is a one-time change. You can just reformat your codebase, optionally add the commit to `.git-blame-ignore-revs`, and be done in (hopefully) less than a minute. For people working in your codebase, the new format is (hopefully) easier to read than the old format, so reverting the change adds a nonzero cost every time someone reads an expression after a guard.

As a maintainer, we would have to pay the cost of maintaining this toggle forever. If Ormolu ever makes changes around this area, merging Ormolu into Fourmolu will cause a conflict we'll have to resolve. This seems hard to justify if no one actually likes that style, but you just want it for backwards compatibility of this one version bump.

Thinking about this more, I don't think it's worthwhile to have this option in Fourmolu. You're always free to fork Fourmolu (or Ormolu) and revert the change in your own repo. I hope that makes sense; please let me know if you feel I'm being unreasonable
