### ISSUE TITLE
Question: changing default-language and default-extensions can result in different formatting behaviour?

### ISSUE THREAD

**Issue by jerbaroo** [fourmolu/fourmolu#373]
Recently updated default-language from `Haskell2010` to `GHC2021` and added a few `default-extensions`:

```yaml
      BlockArguments # added
    , DuplicateRecordFields # added
    , LambdaCase
    , MultiWayIf # added
    , NoImplicitPrelude # added
    , OverloadedLabels
    , OverloadedStrings
```

Running `fourmolu` after these changes introduced formatting changes that don't really seem to correspond to those changes in `default-language`/`default-extensions` e.g. :

![image](https://github.com/fourmolu/fourmolu/assets/6631452/195ce0f4-c24d-4fb9-86df-ac5a81641622)

Is this expected behaviour?

`fourmolu` and `ghc-lib-parser` versions:
```
fourmolu 0.14.0.0
using ghc-lib-parser 9.6.2.20230523
```

**Comment by brandonchinn178** [comment]
Yes, NoImplicitPrelude will cause Fourmolu to no longer load the fixities for Prelude operators. If you're using a custom prelude, you have to configure the reexports option appropriately. See the README or search for other closed issues about the same issue.
