### ISSUE TITLE
First module re-export with section heading indented too far with leading import-export-style

### ISSUE THREAD

**Issue by roelvandijk** [fourmolu/fourmolu#381]
**Is your feature request specific to Fourmolu?**
- [x] Yes, this feature is not relevant to Ormolu

**Describe the current + desired formatting**

Example code:
```hs
module Bug (
-- * module X re-export indented too far
module X,
-- Foo indented normally
Foo
) where
```

Formatted with `import-export-style: leading`:

```hs
module Bug
    ( -- * module X re-export indented too far
        module X
    -- Foo indented normally
    , Foo
    ) where
```

Desired formatting:
```hs
module Bug
    ( -- * module X re-export indented too far
      module X
    -- Foo indented normally
    , Foo
    ) where
```

This bug/oddity does not occur in Ormolu because it doesn't have a leading import-export-style.
It only occurs when the first exported item is a module re-export with a haddock section heading. Removing either the section heading (`-- *` -> `--`) or module (`module X` -> `X`) gets rid of the extra indentation.
It does not occur for any following module re-exports with section headings.
The amount that the module re-export is indented too far is semi-indepenent from the `identation` setting.
With _odd_ indentation the extra indentation is 3.
With _even_ indentation the extra indentation is 4.

**Comment by brandonchinn178** [comment]
Seems to be a regression in 0.13, caused by this PR: https://github.com/fourmolu/fourmolu/pull/344

Looking into how to handle both cases...
