### ISSUE TITLE
Add single-deriving-parens

### ISSUE THREAD

**Issue by pbrisbin** [fourmolu/fourmolu#385]
**Describe the option you'd like to add**

`single-deriving-parens: always|auto|never`, to be consistent with [`single-constraint-parens`](https://fourmolu.github.io/config/single-constraint-parens/) but for `deriving` stanzas.

**Show a code example exemplifying the different option settings**

`single-deriving-parens`: `always` (default):

```hs
-- Given
data X = X
  deriving stock Show

data Y = Y
  deriving stock (Show)

-- Formats too
data X = X
  deriving stock (Show)

data Y = Y
  deriving stock (Show)
```

`single-deriving-parens`: `auto`:

```hs
-- Given
data X = X
  deriving stock Show

data Y = Y
  deriving stock (Show)

-- Formats too
data X = X
  deriving stock Show

data Y = Y
  deriving stock (Show)
```

`single-deriving-parens`: `never`:

```hs
-- Given
data X = X
  deriving stock Show

data Y = Y
  deriving stock (Show)

-- Formats too
data X = X
  deriving stock Show

data Y = Y
  deriving stock Show
```

**Comment by brandonchinn178** [comment]
I assume auto should be Show => Show, (Show) => (Show)?

Makes sense, PR welcome!

**Comment by pbrisbin** [comment]
> I assume auto should be Show => Show, (Show) => (Show)?

Yeah, I think I show (heh) exactly that as my second example right?

**Comment by brandonchinn178** [comment]
No, it looks like you have Show => (Show) twice

**Comment by pbrisbin** [comment]
I've started on this and hit what I think is a road block.

Using `single-constraint-parens` as a guide, I believe the way to do this is to modify the `everywhere` walk in `Parser.hs` to operate on `DerivClauseTys`.

However, unlike constraints, this type seems to encode parenthesis-vs-not as different constructors.

![](https://files.pbrisbin.com/screenshots/screenshot.1413551.png)

In other words, I **think** this is how it would work:

- `deriving Eq` -> `DctSingle _ Eq`, whereas
- `deriving (Eq)` -> `DctMulti _ [Eq]`

I can easily write a pass to do what I want (e.g. change `[Eq]` to `Eq` if I want to remove parenthesis),

```hs
    patchDeriving :: DerivClauseTys GhcPs -> DerivClauseTys GhcPs
    patchDeriving = \case
      DctSingle dict sigType
        | DerivingAlways <- derivingParens -> DctMulti dict [sigType]
      DctMulti dict [sigType]
        | DerivingNever <- derivingParens -> DctSingle dict sigType
      x -> x
```

But this is very much changing the AST, which makes things very angry,

```
       Got ormolu exception:

       data/fourmolu/single-deriving-parens/input.hs
       @@ -1,7 +1,7 @@
         module Main where

         data Foo = Foo
       -     deriving stock Show
       +     deriving stock (Show)

         data Bar = Bar
             deriving stock (Show, Eq)

         AST of input and AST of formatted code differ.
           at data/fourmolu/single-deriving-parens/input.hs:4:20-23
           at data/fourmolu/single-deriving-parens/input.hs:10:20-25
         Please, consider reporting the bug.
         To format anyway, use --unsafe.
```

Am I on the right track? Is there a way to say "no, I do mean to change the AST"?

**Comment by pbrisbin** [comment]
I feel like I'm missing something, because the constraints code is inserting or removing extra `HsParTy` nodes, which I would've also expected to register as a change to the AST... :thinking:

**Comment by pbrisbin** [comment]
Ah thank you!

At first glance, it actually seems to already be doing what I'd think I'd need to add,

```hs
derivedTyClsParensEq (DctSingle NoExtField sigTy) dct' = genericQuery (DctMulti NoExtField [sigTy]) dct'
```

But I'll keep digging.

**Comment by pbrisbin** [comment]
Completed in #386.
