### ISSUE TITLE
Fourmolu fails to format haddock docs for infix constructors

### ISSUE THREAD

**Issue by MangoIV** [fourmolu/fourmolu#388]
**Is your bug specific to Fourmolu?**
- [x] Yes, I've verified that Ormolu does not have this bug

**Did you try it on the web app?**
- [x] Yes, I've verified that https://fourmolu.github.io can reproduce this bug

**Did you search for existing issues?**
- [x] Yes, there are no open or closed issues related to my issue

**Describe the bug**
Provide steps to reproduce the bug, and what the expected behavior should be.

switching on leading function arrows makes fourmolu fail on this code: 

```haskell
-- | a payload to receive or return
type data Payload
  = -- | no Payload
    None
  | -- | payload of that type, encoded as that content type
    Type :~ ContentType
  | -- | an unstructured payload (example, Html)
    P ContentType
```

```
<interactive>
@@ -2,7 +2,8 @@
type data Payload
= -- | no Payload
None
- | -- | payload of that type, encoded as that content type
- Type :~ ContentType
+ | Type
+ -- ^ payload of that type, encoded as that content type :~ ContentType
| -- | an unstructured payload (example, Html)
P ContentType
+

AST of input and AST of formatted code differ.
at <interactive>:6:5-23
Please, consider reporting the bug.
To format anyway, use --unsafe.
```

unsafe really messes this up, too, so it's really unsafe. 

This does not happen with trailing function arrows.

**Comment by brandonchinn178** [comment]
This is more of an issue with GHC/Haddock + Ormolu:
* https://gitlab.haskell.org/ghc/ghc/-/issues/24221
* https://github.com/tweag/ormolu/issues/758

I'll keep the ticket open for tracking, but I don't think there's much we can do for this

**Comment by MangoIV** [comment]
The same bug doesn’t happen on ormolu available on nixpkgs

**Comment by brandonchinn178** [comment]
This exact symptom is not a bug in Ormolu, you're right. But the root cause of this bug is that GHC attaches the docstring to the first argument, not the constructor. And Ormolu has a bug with documenting arguments of infix constructors.

Even if Fourmolu makes the change you want, it won't work correctly; the haddock comment will show on the constructor argument, not on the constructor. The only way to do what you wabt is to rewrite your constructor as:

```hs
| -- | docs
  (:-) Type ContentType
```

**Comment by brandonchinn178** [comment]
This seems to work now, with GHC 9.10

**Comment by MangoIV** [comment]
neat, thanks
