### ISSUE TITLE
specify alternate configuration file

### ISSUE THREAD

**Issue by teto** [fourmolu/fourmolu#396]
I would like to embed the configuration file with ormolu so that the same config can be used in various projects.

we provide fourmolu via nix and one of the common ways to do this in nix is to wrap the executable so:
1/ Ideally I would create a fourmolu-new wrapper that calls `fourmolu --config /nix/store/....-config`
2/ One solution is to create a wrapper fourmolu-new that  calls fourmolu with options passed on the command line. But I prefer to edit the file with comments rather than the command line
3/ My other idea since fourmolu looks for a config in XDG_CONFIG_HOME is to change the value of this variable to a folder in the nix store with the config. It's convoluted.

Is such a command line option desirable ? what do you suggest ?

**Comment by brandonchinn178** [comment]
Sure, we could add a `--config` option! Feel free to open a PR!

**Comment by teto** [comment]
thank you \o/
