### ISSUE TITLE
Option to not format comments at all via a formatting config

### ISSUE THREAD

**Issue by xave** [fourmolu/fourmolu#401]
At times one is in a `do-block` doing exploratory coding. In such cases, some lines might be commented and uncommented to facilitate rapid prototyping. At present it seems that `fourmolu` removes all indentation from a comment, pulling it to the beginning of the line. The issue is that when that line is later uncommented, it does not always go back to the original indentation. Thus, if one lints on save, the entire `do-block` and likely surrounding nested code gets its formatting garbled. 

Often, the line I am commenting out is perfectly indented to where it should be in the code. It would be nice to be able to tell fourmolu to not effect the formatting of comment strings at all, perhaps via a config flag.

## Example

With a piece of code such as:

```
foo
    $ bar
    $ baz
```
one might comment it out together.
```
--foo
--    $ bar
--    $ baz
```

`fourmolu` then sees a string right next to `--` and adds a space.

```
--␣foo   <--------------space added to this line automatically
--    $ bar
--    $ baz
```

But now when you go to uncomment, all of that block of stuff is no longer correctly spaced with respect to itself. This then causes the entire file to be incorrectly spaced. 

### Proposed Solution
The ideal solution in my mind would be that with this formatting flag, one could choose to not have the indentation and/or spacing on their comment lines altered at all. Only uncommented lines (and perhaps special inline documenting comments) would be reformatted.

**Comment by brandonchinn178** [comment]
I don't fully understand. Is the issue just about whether a space should be automatically added to the beginning of a comment or not? Fundamentally, I don't think it's worth the effort to improve styling in-progress code. Say we add a flag that does this. You probably don't want to allow comments like `--asdf` when actually committing, so you'd probably want to turn on the flag on save then turn it off on commit, which isn't easily supported.

Ultimately, I think you're just going to run into these kinds of issues with formatting on save. What if you have an if-expression and want to just test the `else` branch for a second? If you comment out the first two lines, that unindents the else block because at that point in time, it's _not_ an else block, so it shouldn't be formatted as one.

**Comment by xave** [comment]
Thanks Brandon,
Could you please describe what you mean by “in progress code?” Is it code that partially implements a feature? That is part of a refactoring effort? Is it code just touched a few seconds ago? Code to be committed? To be merged? Committed code is not the same as merged code, after all. For instance one could have multiple commits to a PR. 

## On comments that need to retain their structure
There are valid reasons to have commented code that needs its structure maintained. If one is mocking around an API involving network calls, for instance, it could make sense to comment out part of the code that does generic network calls and to add a chunk of code that hard codes a similar call for testing an updated implementation. That hard coded test code could very well be worthy of committing or even merging. Yet there would be value in retaining the actual functionality in place (by commenting it out). Similar logic applies for a database application. These are scenarios where there is likely to be nested monadic code and changing the formatting of all the code because of the current behavior could (and often has happened for me) have cascading effects on most of the file. 

While one might simply undo in the case of a format on save, in a scenario I just described, there is the likelihood that reverting such a change does not happen until much later, yet `fourmolu` will have had affected the editing immediately (whether on save, on file close, on running the command manually, on merging). In other words, `fourmolu` changing the spacing within a commented code might not be noticed or relevant until some later time when it happens to be uncommented. Whether this happens on save or commit does not affect this situation. 

In short, not all exploratory code is just messing around and hacking with lines trying to get stuff to work. There are principled reasons for needing formatting to either remain untouched or to be maintained even within a comment. All code is “in progress“ until each feature is fully implemented, integrated, and tested. One could say most code that exists is “in progress” perpetually.  

## On reversibility and consistency
With the above stated, the issue is not the addition of the single space (in the previously provided example), but the fact that it modifies the block by applying it to the first line _only_ of that block.

`fourmolu` edits to comments should be reversible whether done "on save" or a year later because of the fundamental nature of what comments are. We already have special notation for documentation comments, yet there are also in place code snippets and unstructured prose. These apply to any programming language. 

Right now, if you block comment, an _ad hoc_ space is added to one line of a block of code `fourmolu` had just previously understood and correctly formatted. It introduces a spacing error that the dev did not make. That error can then cause the entire file to be improperly formatted once the comment is removed. 

Ideal functionality: 
```
Comment multiple lines -> 
fourmolu formats (or does not as proposed) ->
uncomment ->
back to normal. 
```

At the moment, you comment and fourmolu does a thing it later gets confused about.

## Possible approaches

One approach is to have an option to not touch comments at all. This is actually the most hands-off option for `fourmolu` as it only requires not doing anything with lines beginning with `--` or whitespace and then `--`.

Another approach is to have the parser detect the comment token `--` (which it already can do) and to then apply the typical formatting rules on any block of contiguous comment lines. Presumably both parts of this are already possible and need to just be composed in this way. It seems like at the moment there is just _ad hoc_ logic for the formatting of comments themselves from the behavior. 

If it does this proposed way, it would prepend a space to not only the first line, but also to all code beneath. Thus when you uncomment, there are no conflicts with the rest of the code. The comment symbol, in this case,  might be thought of as the beginning of a "line". We keep the comments to whatever block it was indented to and process what’s in the comments as if it is actual code. 

Again, I’d much rather just have an option to have `fourmolu` not touch comments at all or their indentation except perhaps for `haddock` style comments. Then I could format the code with `fourmolu`, comment out my block, and go on with my day. When I later uncomment, it is already formatted from before, so no change. 

While it does make sense that `fourmolu` formatting of code itself should have a finality to it, the very nature of what a comment is means that the effects a code formatter has on them should either be uneffectful or reversible.

**Comment by brandonchinn178** [comment]
So ultimately, this isn't possible. Fourmolu/Ormolu "attaches" comments to a particular AST node and formats the comments with the AST node. It can't just "leave the comments where they are" because lines might change as code higher up gets formatted to additional lines.

IMO a formatter should also be responsible for formatting comments. I don't think it wouldn't be considered good formatting to allow

```hs
foo = do
  x <- bar

  -- asdf
    -- asdf
  -- asdf
  y <- baz

           -- comment
  z <- thing x y
```

But regardless whether this is desired or not, it's just not really possible with the current implementation of Ormolu/Fourmolu.

---

As an aside, what if you comment out with multiline comments?
```hs
foo = do
  {-
  x <- bar
  thing
    $ baz
    $ asdf
  -}

  y <- other
```

That should leave formatting alone, I think

**Comment by xave** [comment]
Just to make sure we are on the same page here, this entire thread is not about the aesthetics of how many spaces should be after a comment symbol (`--`) or of arbitrary nesting of comments. Rather, this thread is about the practice of software engineering using `fourmolu` as a tool and how the current implementation of it adversely effects daily programming in a specific scenario, to be expanded on for clarity below. 

Aesthetics are important. This is clearly good. 

``` 
-- foobar
```

We are and have been in complete agreement there. 

With that being stated, we have a form vs. function situation.  The function of Haskell code is to properly compile (performing some function when run). The focus of this thread is that a certain aesthetic decision is manifesting *in such a way that* it impacts functionality and ergonomics of working with code. 

With most editors, if you block select and comment that selection,  it will add `--` it to the beginning of the text without adding a space afterwards. This is natural. In the case of formatting such comments, `fourmolu` is doing a specific behavior that I will elaborate on explicitly below.

`*` will denote spaces added by the developer.
`+` will denote spaces added by `fourmolu`.

```
Stage 1 - baseline (unannotated)

makeContact = do
    getPerson
        $ first 
        $ last 
    getAddress
	$ street
        $ zipCode
	$ city
```

```
Stage 1 - baseline (annotated)

makeContact = do
****getPerson
********$ first 
********$ last 
****getAddress
********$ street
********$ zipCode
********$ city
```

So far, so good. Now we decide to comment out `getAddress` and all of its arguments.

```
Stage 2 - comment out monadic

makeContact = do
****getPerson
********$ first 
********$ last 
****--getAddress
****--****$ street
****--****$ zipCode
****--****$ city
    ^^
    comments are here.
```

```
Stage 3 - fourmolu formats

makeContact = do
****getPerson
********$ first 
********$ last 
****--+getAddress   <-------- fourmolu has added a space (+)
****--****$ street  <-------- now instead of 4 spaces indented, there are 3
****--****$ zipCode <-------- same goes for here
****--****$ city    <-------- and here
```

So the entire block is garbled. Not noticed by the dev at first because everything is a comment anyway. But look at what happens the moment we uncomment...

```
Stage 4 - uncomment formatted code

makeContact = do
****getPerson
****|***$ first 
****|***$ last 
****+getAddress   <-------- this is now nested into getPerson
********$ street  
********$ zipCode 
********$ city    
```

`fourmolu` rightfully says "Hey! That `getAddress` thing is nested inside of `getPerson`, but the spacing is off. No worries! It must be an argument to it. Let's rearrange.

```
Stage 5 - this code won't compile
makeContact = do
****getPerson
********$ first 
********$ last 
****++++$ getAddress   <-------- this is now nested into getPerson
********++++++$ street  
********++++++$ zipCode 
********++++++$ city    

-----------

ghc error saying that we provided three argmuments to `getPerson` but it only takes two
```

Compilation breaks *and* the dev has to fix all those lines manually, which defeats the purpose of using `fourmolu` to automatically style things. All of this is due to the fact that commenting and uncommenting isn’t done in a way that it is reversible. 

## on AST
You mentioned that `fourmolu`/`ormolu` uses an AST. That is great! That means even more ability to guide this comment behavior than I had alluded to in my proposed solutions. 

“Ignoring comments” can be restated as “doing *nothing*" to comments which is the same as applying an `identity` function to those lines. I say "*an* `identity` function", because it might slightly alter the text (such as adding a space to every line in the block). Something is already being applied to this lines already, so this would be a matter of modifying that applied function to either handle an option to keep identity or to add a space to every line contiguous to that block comment. The test would be that if you remove the comment markers `fourmolu` would automatically clean up the spaces and align things. I do believe it actually does that today! If not for solitary space added to the first commented line only it would already work as proposed. So the fix is essentially as stated or similar. 

Consider this alternative scenario:

```
Stage 3 - fourmolu formats (alternate approach)

makeContact = do
****getPerson
********$ first 
********$ last 
****--+getAddress    <-------- fourmolu has added a space (+)
****--+****$ street  <-------- 4 spaces maintained ✅
****--+****$ zipCode <-------- 4 spaces maintained ✅
****--+****$ city    <-------- 4 spaces maintained ✅
```

Now, if the dev removes the `--+` (comment plus extra space), everything else is already aligned as it was before commenting.  

`X` means deleted by dev

```
Stage 4 - uncomment formatted code (alternate approach)

makeContact = do
****getPerson
********$ first 
********$ last 
****XXXgetAddress    
****XXX****$ street  
****XXX****$ zipCode 
****XXX****$ city    
    ^^^
    deleted by dev
```
```
Stage 5 - after uncommenting, identical to baseline ✅

makeContact = do
****getPerson
********$ first 
********$ last 
****getAddress
********$ street
********$ zipCode
********$ city
```

This is much preferred to the current state of things from a pragmatic standpoint. While you have to also remove the extra space when uncommenting, at least the spacing of all the nested code with respect to itself is maintained.

**Comment by brandonchinn178** [comment]
A few things here:

1) IMO this is more of an issue with the editor. I use Sublime Text primarily, and the comment hotkey does include a space. With vim, you could do Ctrl+V then Shift+I and add two dashes and a space to all lines at once. I think this is best fixed at the editor level.

2) It's still not clear to me why your recommendation is okay, but the current situation is not. In your last suggestion, you say each line would have an extra two dashes and a space, and the developer would just have to remember to delete the extra space on each line before running Fourmolu. That's the same as right now, except the developer just has to remember to delete the extra space on the first line before running Fourmolu. What's the difference?

The only difference I see is that *while* it's a comment, the code is correctly indented. Which I don't think is worth fixing, because it's just a comment.

3) It does seem like there is a spot we could apply a space to all lines if we add it to the first line (or any of the lines). But it wouldn't change anything if all the lines have spaces in it:

```hs
{- initial -}
do
  --line1
  --  line2

  --  line3
  --  line4

{- after adding space to the first block -}
do
  -- line1
  --   line2

  --  line3
  --  line4

{- removing two dashes and a space -}
do
  line1
    line2

   line3
   line4
```

The second block is now misaligned with the first, which is probably not what you want. I'm not sure how Fourmolu can help here.

4) If (3) is fine, this would potentially be equally applicable to Ormolu. I'd recommend opening an issue to Ormolu first, and if they reject it, we can see about adding an option in Fourmolu.

**Comment by xave** [comment]
With respect to (1), the larger issue in my eyes is having to be so precise with commenting in the first place. The thing is, that as far as actual code formatting, I am satisfied here. Yet, for instance, if I go to the very beginning of the line and add my comments there, this sort of garbling on uncomment happens still. For instance, I never faced any of these issues in the now unmaintained `brittany`. My dev workflow changed once moving to the `fourmolu`/`ormoulu` family. 

With respect to (2), I am merely trying to provide solutions along with my statement of the problem. In all likelihood, there is an even more elegant solution to this than I have ever stated here.

Regarding (3), I agree that my solution of just adding a space to the block breaks down if, for instance, there had already been commented out code that the newly created block now "merges with". So one could add a space to things that don't even need it. 

Ultimately, it seems that we have to be too careful with the manner in which we initiate a comment with respect to how it is then formatted than is necessary. This manifests in such a way as to hinder the expressivity of how one codes that are not actually unreasonable and are in fact supported by the language itself. All of this leads back to the idea of allowing a flag that prevents or does minimal modifications to a commented block (such as aligning it to the nearest indented block while not adding spacing). I would think that the single line behavior (of adding that space) can be maintained while turning off such reformatting for a block of things to prevent this sort of block-unaware reformatting within the comment is a balance in lieu of some more elegant solution. For now, I will just add a space after my comment symbol `-- `.

**Comment by brandonchinn178** [comment]
I'm leaning towards not doing this, as Fourmolu shouldn't optimize for enabling temporary messiness. IMO if you're committing code, it should be well formatted (who knows how long it'll be in the messy state), so you can take the extra couple seconds to use multiline comments instead of your IDE's comment shortcut.

I will close this for now until someone else voices a desire for this.

**Comment by xave** [comment]
The `fourmolu` tool, from its conception,  has been about allowing small tweaks to opinionated config of `ormolu`. In the case where one wants most but not all of the default behavior, allowing it to be simply turned off is a "small tweak". The least effort proposal here is to just allow comments to not be formatted by `fourmolu` with an appropriately set config flag. As someone doing a lot of development in Haskell, and not just one-off academic experiments, this is absolutely an important feature, and it is outside the scope of `ormolu`, the formatter that does not allow and was not founded on the configurable choice of using four spaces.

**Comment by xave** [comment]
This is definitely a bug. I just commented out a line in a `stack.yaml` and it nested that line two levels deeper (the option above) when it should have just left it at the top level. If `ormolu/fourmolu` is going to be this aggressive with comments, this feature really does need to be able to be turned off. Sometimes the best outcome is to let the thing lay where it is. 

Reminder that `fourmolu` was created in order to provide necessary micro-configuration to `ormolu`. Thus my request is largely outside of the scope of `ormolu` itself. This is definitely in the same vein as 2 vs 4 spaces.

**Comment by xave** [comment]
My mistake. However, it does highlight the point of this thread. Multiple formatters are doing the same sort of thing with comments--formatting them in a way that they cannot restore the initial nesting upon uncomment.

**Comment by georgefst** [comment]
I'm sympathetic to this, since I do find it annoying when commented-out code gets moved around. But I believe the proposed general fix, of not moving _any_ comments at all, would be near-impossible to implement, for the reasons @brandonchinn178 has mentioned. A more specific fix, optionally disabling the spaces we add to the starts of comments (#255), is feasible, but of limited utility given that, as discussed, it is easily worked around by mimicing what most editors already do.

There are other cases where we move comments around in ways which can be annoying, notably #72 (which is my biggest current gripe with Fourmolu). But I think we're best off dealing with these too on a case-by-case basis.
