### ISSUE TITLE
Trailing $ vs leading operators seems inconsistent

### ISSUE THREAD

**Issue by pbrisbin** [fourmolu/fourmolu#405]
Test on https://fourmolu.github.io/, with default configuration:

![](https://files.pbrisbin.com/screenshots/screenshot.2199009.png)

The top expression uses only `$` and fourmolu stair-cases it with trailing-operator style. The bottom expression, IMO, is the "same", but it uses `.`-`$`, and fourmolu makes it a nice, aligned, operator-first format.

I **always** want leading-operator, and find myself moving expressions to the `.`-`$` style just to get fourmolu to do it. It feels icky to change things just to appease a formatter, so I thought I'd report and ask about it.

**Comment by brandonchinn178** [comment]
Semi-related: #46 #166 #315 tweag/ormolu#692

This is due to the fact that $ is special and can allow a block to hang. If you want to disable that feature everywhere, I'd be open to a PR that adds a config option to turn off hanging behavior for $

**Comment by pbrisbin** [comment]
Ah good point, well I would **not** want to see code formatted like,

```hs
bar
    $ do
```

Is that would happen if I "disable[d] that feature everywhere" ?

**Comment by brandonchinn178** [comment]
Yeah, it would. We could try to make the config option "only hang if there's only one $ in this chain of operators", but not sure how complex that would be to determine in the code

**Comment by pbrisbin** [comment]
I see. Well thank you for the explanation, I'm unlikely to get to a PR for something like that any time soon. Do you think it's worth keeping this Issue open?

**Comment by pbrisbin** [comment]
Actually, disabling everywhere might probably be OK, as long as column width is applied consistently.

Here are some examples, if we assume an 80 column with.

```hs
someShortFunction $ someShortFunction x

someShortFunction $ someShortFunction $ \x -> do
  -- ...

someLongFunction
  $ someLongFunction
  $ someLongFunction
  $ someLongFunction
  $ someLongFunction x

someLongFunction
  $ someLongFunction
  $ someLongFunction
  $ someLongFunction
  $ someLongFunction x

someLongFunction
  $ someLongFunction
  $ someLongFunction
  $ someLongFunction
  $ \x -> do
    -- ...
```

If that's how it would work out, that seems good.

**Comment by pbrisbin** [comment]
I opened by work so far as a Draft PR: #444.

**Comment by brandonchinn178** [comment]
When you run `stack exec fourmolu`, it's still using the fourmolu.yaml config file, as usual, which you can see in the output. That file contains the defaults for ormolu.

The test is the correct behavior, because it sets the configuration explicitly. In the CLI, you might want to explicitly set the `--hanging-dollar` flag

**Comment by brandonchinn178** [comment]
When you run `stack exec fourmolu`, it's still using the fourmolu.yaml config file, as usual, which you can see in the output. That file contains the defaults for ormolu.

The test is the correct behavior, because it sets the configuration explicitly. In the CLI, you might want to explicitly set the `--hanging-dollar` flag

**Comment by pbrisbin** [comment]
But I've not implemented any behavior changes yet. The option is effectively ignored. What is making the test do something different (and what I want no less)?

**Comment by brandonchinn178** [comment]
Maybe you're reading the test output wrong? The - lines are what's in the output file, the + lines are what fourmolu is returning

**Comment by pbrisbin** [comment]
> The - lines are what's in the output file, the + lines are what fourmolu is returning

Hmm, maybe?

```
       --- actual
       +++ expected
```

I was reading this as `---` is what fourmolu actually outputs, and `+++` is what the file describes as expected. What you say seems backwards from that.

Also, the failing test is `output-True.hs`, which [contains stair-case code](https://github.com/fourmolu/fourmolu/pull/444/files#diff-b18b4610c93325b08199eb46163905c4620c16c289b8f534b0e25dae56ce51e1) -- so the only way that would fail (regardless of what the diff looks like) is if fourmolu outputs operator-first code, right? I really feel like I'm reading things correctly :thinking: .

**Comment by pbrisbin** [comment]
OK, the plot thickens. Within a project, I made two identical files at different paths:

- `In.hs`
- `src/Project/In.hs`

Formatting `In.hs` received hanging, stair-case formatting, while the file in `src/` received operator-first formatting.

So that must be it. Being under `src/` tells it something about the package that triggers operator-first?

I think this explains why the behavior has been driving me absolutely batty for years. When it does or doesn't choose this form is extremely nuanced and pretty difficult to isolate. I used to think `v0.14+` introduced this hanging style, but I think it may be that it introduced something about utilizing the package context that just causes it to happen more...

**Comment by pbrisbin** [comment]
OK, I've done a number of other tests and found the following:

- Module is not listed in cabal file -> hanging-stair-case
- Module is listed in cabal file, with no dependencies -> operator-first
- Module is listed in the cabal file, with `base` dependency -> hanging-stair-case
- Explicit fixity of `infixr 0 $` applied to _any_ of the above scenarios -> hanging-stair-case

I don't know what to make of this, what to call a bug (if anything), or how to fix. I'm going to stop here and wait for some guidance.

<details>
<summary>Test output</summary>

```console
% ls
In.hs  foo.cabal  src  sub
% ls sub
In.hs  bar.cabal  src
% cat foo.cabal
cabal-version: 1.18

name:           indirect
version:        1.0.0.0

library
  exposed-modules:
      Foo.In
  hs-source-dirs:
      src
  build-depends:
      base<5
% cat sub/bar.cabal
cabal-version: 1.18

name:           indirect
version:        1.0.0.0

library
  exposed-modules:
      Bar.In
  hs-source-dirs:
      src
% for x in **/*.hs; do echo $x; fourmolu $x; echo; done
In.hs
foo =
    bar $
        bar $
            bar $
                bar $
                    bar $
                        bar $
                            bar $
                                baz bat

src/Foo/In.hs
foo =
    bar $
        bar $
            bar $
                bar $
                    bar $
                        bar $
                            bar $
                                baz bat

src/In.hs
foo =
    bar $
        bar $
            bar $
                bar $
                    bar $
                        bar $
                            bar $
                                baz bat

sub/In.hs
foo =
    bar $
        bar $
            bar $
                bar $
                    bar $
                        bar $
                            bar $
                                baz bat

sub/src/Bar/In.hs
foo =
    bar
        $ bar
        $ bar
        $ bar
        $ bar
        $ bar
        $ bar
        $ baz bat

sub/src/In.hs
foo =
    bar $
        bar $
            bar $
                bar $
                    bar $
                        bar $
                            bar $
                                baz bat
```

</details>

**Comment by brandonchinn178** [comment]
Ah sorry, yes you're reading the output correctly.

So the only way staircase formatting works is if Fourmolu recognizes `$` as the `$` from base; otherwise, it follows normal infix operator precedence formatting. In other words, Fourmolu already has the operator-first behavior in the world where it doesn't recognize the operator.

Looking at the test framework, it looks like we don't specify `cfgDependencies` in the ormolu config, which means when the test suite is formatting a file, it doesn't include the operator fixities from anything, even `base`. Can you try adding `cfgDependencies` like here: https://github.com/fourmolu/fourmolu/pull/445?

**Comment by pbrisbin** [comment]
> the only way staircase formatting works is if Fourmolu recognizes `$` as the `$` from `base`; otherwise, it follows normal infix operator precedence formatting

This makes conceptual sense. I'm a little confused by my test cases:

1. Module is not present in cabal file at all -> stair-case
2. Module is listed, with no dependencies -> operator-first
3. Module is listed, with base dependency -> stair-case

I'm particularly confused by (1), which I would image shouldn't be able to tell that it's `base`'s `$` and so should go operator-first. Not particularly important just another wrinkle of confusion in this feature that I'd like to note :shrug: 

> Can you try adding `cfgDependencies` like here

Yeah, will do.

**Comment by pbrisbin** [comment]
Adding the dependency made my tests fail in the expected way. Now I can get to work making them pass, thanks!
