### ISSUE TITLE
CI: cache logic unnecessarily complicated

### ISSUE THREAD

**Issue by andreasabel** [fourmolu/fourmolu#407]
https://github.com/fourmolu/fourmolu/blob/768505e5a7895f296e3e0029e702b66f04dbf686/.github/workflows/ci.yml#L50-L61

Note that cabal freeze files contain the hackage index time stamp, so they are different basically on each CI run, certainly every day.  Thus, the complication `CURR_MONTH` to "manually" change the cache key every week is obsolete.

**Comment by brandonchinn178** [comment]
hm interesting. I thought I saw that in some blog post... I can remove it.

**Comment by andreasabel** [comment]
Some CIs remove the time-stamp from the freeze file with some `sed` magic, that would be the (maybe better) alternative.
