### ISSUE TITLE
9.10 support

### ISSUE THREAD

**Issue by michaelpj** [fourmolu/fourmolu#412]
`ormolu` has it as of 0.7.5.0, so probably just need to merge that in.

**Comment by brandonchinn178** [comment]
Yes, I have it on the list, just on vacation now. Will get to it shortly!

**Comment by dhess** [comment]
Thanks! Any idea when a new Hackage release will be cut with this change?

**Comment by brandonchinn178** [comment]
https://github.com/fourmolu/fourmolu/milestone/1

I'm currently planning by end of this week, unless you need it more urgently?

**Comment by dhess** [comment]
No, that is excellent, thank you!
