### ISSUE TITLE
Optionally sort constraint tuples

### ISSUE THREAD

**Issue by michaelpj** [fourmolu/fourmolu#427]
**Is your feature request specific to Fourmolu?**
Conceivably this could be done by `ormolu` but I expect this to be a bit of a "love it or hate it" feature, so probably needs to be configurable.

**Describe the current + desired formatting**
I _think_ I would like the option to have constraint tuples _sorted_. The issue is that in code which has a lot of constraints, you often have similar or identical constraint tuples that _look_ quite different due to irrelevant differences in the order. If they were sorted it would make it easier to see the similarities or differences.

To put it another way, at the moment I have to manually make an arbitrary decision about where to add a constraint into a constraint tuple. In such a situation where it is arbitrary I think it's arguable that the formatter should decide, like for imports.

e.g. (before)
```hs
doAtThing ::
  (IOE :> es, Concurrent :> es, SomethingElse :> es, EvenMore :> es, ThatsRightMore :> es, IsThisTooMuch :> es) =>
  Args ->
  Eff es ()
```
vs (after)
```hs
doAtThing ::
  (Concurrent :> es, EvenMore :> es, IsThisTooMuch :> es, IOE :> es, SomethingElse :> es, ThatsRightMore :> es) =>
  Args ->
  Eff es ()
```

Note that even if you used this option you could still group sets of constraints together if you want to by using multiple `=>`s.

If we did this I'd want it to apply everywhere we have constraint tuples.

**Comment by brandonchinn178** [comment]
You could probably also group sets of constraints by nesting tuples
```hs
foo ::
  ( (FooA a, FooB a)
  , Bar a
  ) =>
  ...
```
I think this sounds reasonable to me; a first order pass could be to just order alphabetically?

**Comment by michaelpj** [comment]
I've just raised this upstream too just in case they want it, although I doubt it.
