### ISSUE TITLE
Consistency between CLI and YAML config

### ISSUE THREAD

**Issue by georgefst** [fourmolu/fourmolu#50]
The text representations of options are currently specified independently in `FromJSON` instances and `ToCLIArgument` instances. I discussed this with @kukimik at #44, and we determined that what we *really* want is a general-purpose config management library (some examples from other languages are linked in #44). But we could certainly do something simpler here for now, then maybe think about extracting that in to a library.

**Comment by kukimik** [comment]
https://alexpeits.github.io/harg/ may be relevant.

**Comment by georgefst** [comment]
Ooh, that looks very promising!

How did you come across it? I spent a while looking for that sort of thing...

**Comment by kukimik** [comment]
Well, I've been thinking how to implement it myself. I decided that, given a record, I'll probably only need Template Haskell to create another record with each field wrapped in `Maybe` (or some general `f`) and the analogue of `fillMissingPrinterOpts`. I've never used TH, so I tried to find out how to do it. I also recalled the concept of HKD I'd been reading about while working on #15. This somehow lead me to https://hackage.haskell.org/package/higgledy and, in turn, to https://hackage.haskell.org/package/barbies (it's funny - at this point I remembered that I saw `barbies` while preparing #15 and even considered using it, but it seemed an overkill). A link to https://hackage.haskell.org/package/harg was in the readme.

I agree that this package is unfortunately rather hard to find.

I can't have a closer look at this library in the nearest few days. My back and eyes need some rest. However, I'm going to return to this topic. The discussion in https://github.com/alexpeits/harg/issues/16 looks interesting and also points to some other solution.

**Comment by parsonsmatt** [comment]
Doing this with Template Haskell should be pretty easy. I wrote [`record-wrangler`](https://hackage.haskell.org/package/record-wrangler) which does something similar - it modifies the names of the fields of a record. It would be straightforward to modify that code to instead apply `Maybe` to each field type. A `RecC` constructor takes a `Name` and `[(Name, Bang, Type)]`. For each entry in the list, you'd write `AppT (ConT ''Maybe) oldType`.

**Comment by georgefst** [comment]
I've only glanced at it so far, but [Conferer has just been released](https://www.reddit.com/r/haskell/comments/lx55pu/ann_conferer_a_configuration_library_for_haskell/), which looks like another option.

**Comment by brandonchinn178** [comment]
Looking into this.

`conferer` doesn't seem very good... for one, it doesn't support `--help`, but I also can't figure out how `conferer` gets the flag name from the field name. e.g. I derived `FromConfig` automatically and am doing
```hs
    main :: IO ()
    main = do
      config <- mkConfig' [] [Cli.fromConfig]
      opts <- fetch config
      print (opts :: PrinterOpts)
```
And I'm trying every combination of `--indentation=2`, `--poIndentation=2`, etc. but nothing's working. Also, the README is outdated with the library 😢 

But actually, taking a step back, we should [try to avoid conflicts](https://github.com/fourmolu/fourmolu/blob/master/DEVELOPER.md#contributing) with ormolu argument parsing, so we should try to still hook into ormolu's argument parsing with optparse-applicative. In light of that, I don't think harg, conferer, or any other library would be good. However, the general motivation of corresponding JSON parsing with CLI parsing is still extremely motivating; I think with a bit of manual type-classing and refactoring, we can still get to a good state while maintaining compatibility with upstream. Will hopefully put up a PR shortly

**Comment by kukimik** [comment]
Thanks to the recent PR the following is no longer relevant in context of the present issue.

@georgefst I stumbled on  https://hackage.haskell.org/package/salak, and having in mind the discussion in #44 I thought that you may be interested. Adding a comment here was the easiest way to let you know.
