### ISSUE TITLE
Please use tags and github releases before hackage ones

### ISSUE THREAD

**Issue by jneira** [fourmolu/fourmolu#55]
Hi, i know there is a maintenance burden that not always have an immediate advantage but been able to sync the repo with hackage releases quickly can help to start hacking the project for testing and bug fixing.

Thanks in advance!!

**Comment by georgefst** [comment]
Noted. I've been meaning to get in to the habit of doing that sort of thing for all the projects I (co-)maintain. Although each Hackage release should at least correspond to a commit like this: 45a8478

**Comment by georgefst** [comment]
Info here: https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases.

I just haven't quite gotten around to looking in to it yet.

We should also document this process in `DEVELOPER.md`.
