### ISSUE TITLE
Place examples in a separate package

### ISSUE THREAD

**Issue by hololeap** [fourmolu/fourmolu#59]
I'm packaging this project for Gentoo, and there doesn't seem to be a way to make the examples included in `data-files` optional. Considering how many there are, it would make sense to make a separate `fourmolu-examples` package so that these ~1100 examples don't have to be included.

**Comment by georgefst** [comment]
Cool. Is Ormolu packaged for Gentoo? This is a fairly light fork so we tend to just follow their lead rather than diverging on this sort of thing.

**Comment by hololeap** [comment]
Yes, it appears it is, but I'm not the one who packaged it. fourmolu happens to be an optional dependency of `haskell-language-server` which is what I'm working on pulling into Gentoo's package tree. Generally, these kinds example files are toggleable in Gentoo, but unfortunately, there's no way to toggle `data-files` in a cabal file using a flag.

**Comment by georgefst** [comment]
Okay. Ormolu is presumably also an optional dependency of HLS, so you'll have the same issue there.

**Comment by hololeap** [comment]
You're right. In any case I opened up a feature request upstream: tweag/ormolu#682

**Comment by georgefst** [comment]
Closed upstream by https://github.com/tweag/ormolu/pull/745 and merged here in #106.
