### ISSUE TITLE
`comma-style: leading` doesn't apply to import and export lists

### ISSUE THREAD

**Issue by typedrat** [fourmolu/fourmolu#61]
I get:
```haskell
module Logging (
  LogAction,
  logMessageStderr,

  -- * Messages
  Message (..),
  HasLog (..),
  WithLog,
  logDebug,
  logInfo,
  logWarning,
  logError,

  -- * Message Severity
  module Colog.Core.Severity,
) where
```

I want:
```haskell
module Logging
  ( LogAction
  , logMessageStderr

  -- * Messages
  , Message(..)
  , HasLog(..)
  , WithLog
  , logDebug
  , logInfo
  , logWarning
  , logError

  -- * Message Severity
  , module Colog.Core.Severity
  ) where
```

This seems like a bug in the option, personally.

**Comment by georgefst** [comment]
You get something close to that with `--diff-friendly-import-export=false`. Admittedly the docs could be clearer.

**Comment by georgefst** [comment]
> You get something close to that with `--diff-friendly-import-export=false`.

Oh wait, actually, no you don't...

We chose to keep the options separate but it is unfortunate that we therefore don't currently support leading commas in import/export lists.

**Comment by telser** [comment]
As a user this would be amazing to have.
