### ISSUE TITLE
Disable pragmas always revert to Ormolu form

### ISSUE THREAD

**Issue by georgefst** [fourmolu/fourmolu#70]
Formatting:
```hs
{- FOURMOLU_DISABLE -}
```

results in the output:
```hs
{- ORMOLU_DISABLE -}
```

As pointed out by @brandon-leapyear in #69.

I should really have thought of this when I added support (a15b229).

One option would just be to make `FOURMOLU` the [canonical version](https://github.com/parsonsmatt/fourmolu/blob/53a57a3bd7bec4beabff4612276365f07edcdd97/src/Ormolu/Processing/Preprocess.hs#L122). But in a sense this just moves the problem. Keeping track of which the user initially used could be mildly tricky.

**Comment by brandon-leapyear** [comment]
I mean, why not just ignore `ORMOLU_DISABLE`? Breaking change, but I don't think there's any point in keeping backwards compatibility with ormolu, especially for this usecase.

**Comment by georgefst** [comment]
You're probably right. It was initially a goal to be able to emulate Ormolu fully, but we've already slipped in a few minor ways (#38), and nobody's complained yet. @parsonsmatt @kukimik Any thoughts?

**Comment by kukimik** [comment]
Keeping compatibility with Ormolu could be beneficial for people who use Ormolu and would like to see how Fourmolu behaves with their code. Changing `{- ORMOLU_DISABLE -}` to `{- FOURMOLU_DISABLE -}` everywhere in my codebase to try out Fourmolu is not much work, but it is some work nonetheless.

Also, if compatibility is dropped, one will have an extra step to do in some cases when comparing the results of Ormolu and Fourmolu, e.g. when testing some changes in Fourmolu.

Another easy solution: make this customizable, perhaps with the following options:
* use `FOURMOLU_DISABLE`, ignore `ORMOLU_DISABLE`;
* use `ORMOLU_DISABLE`, ignore `FOURMOLU_DISABLE`;
* use both `ORMOLU_DISABLE` and `FOURMOLU_DISABLE`, and convert them into `FOURMOLU_DISABLE`;
* use both `ORMOLU_DISABLE` and `FOURMOLU_DISABLE`, and convert them into `ORMOLU_DISABLE`;

Although this sounds somewhat bizarre...

Just an idea. If you decide to get rid of `ORMOLU_DISABLE` I'm not going to protest.

**Comment by georgefst** [comment]
Actually, it should be very easy, and presumably satisfy almost everyone, to just have the last two of those four options.

i.e. Always react to both pragmas, leave it up to the user to decide which to output (with FOURMOLU as the default).

**Comment by kukimik** [comment]
@georgefst Ok, I'll try to implement this solution.
