### ISSUE TITLE
Support different comment types for module and function docstrings

### ISSUE THREAD

**Issue by brandon-leapyear** [fourmolu/fourmolu#74]
I believe it's fairly standard for module docstrings to be of the form
```hs
{-|
Module: Foo.Bar
Description: ...
...
-}
```
and function docstrings to be of the form
```hs
-- | asdf
-- bar
-- baz
```
We should allow module docstrings to be different from function docstrings.

Also, as a bonus, it'd be great if the `{-|` syntax didn't add a space like `{- |`.

**Comment by dpwiz** [comment]
> Also, as a bonus, it'd be great if the `{-|` syntax didn't add a space like `{- |`

Or did, when requested :wink:
