### ISSUE TITLE
AST differs for kind applications in type families

### ISSUE THREAD

**Issue by riz0id** [fourmolu/fourmolu#81]
Fourmolu seems like it doesn't know how to parse lhs type applications in a closed type family regardless of language pragmas.
```haskell
type PickType :: forall k. Nat -> k
type family PickType n where
  PickType @Type 1 = Bool
  PickType @(Type -> Type) 2 = Maybe
```
The same goes for data families.
```haskell
data M :: Nat -> Type

type PickType :: forall k. (k -> Type) -> Type
data family PickType m

data instance PickType @Nat M where
  Foo :: PickType M
```

**Comment by georgefst** [comment]
Thanks for the bug report. I've just checked and this happens with Ormolu as well, so it'd be better off being fixed upstream. Could you please [open an issue there](https://github.com/tweag/ormolu/issues)?

**Comment by georgefst** [comment]
@parsonsmatt Could we perhaps add something to the issue template, prompting people to open issues with Ormolu when appropriate?

**Comment by brandonchinn178** [comment]
Seems to be fixed now 🎉 

FYI @georgefst the bug report template now prompts people to check Ormolu: https://github.com/fourmolu/fourmolu/blob/main/.github/ISSUE_TEMPLATE/bug-report.md
