### ISSUE TITLE
Leading arrows in types

### ISSUE THREAD

**Issue by dpwiz** [fourmolu/fourmolu#86]
Basically a revert of the [original PR](https://github.com/tweag/ormolu/pull/392/files), put under an option.

There is another fork that appears to track this: https://github.com/google/ormolu

**Comment by expipiplus1** [comment]
As much as I love leading arrows in types, I do think there's value in having the `::` on the same line as the identifier as it makes grepping (when HLS isn't working) for some definition easier. Is it possible to have an option for this too when you make your PR @dpwiz :wink:

**Comment by expipiplus1** [comment]
I cherry picked the leading arrow change from that fork, it's on top of my alignment branch here https://github.com/expipiplus1/fourmolu/tree/joe-align-leading-arrow

**Comment by dpwiz** [comment]
Cool. Making it optional is where I crashed :sweat_smile:
