### ISSUE TITLE
Monad comprehensions unimplemented

### ISSUE THREAD

**Issue by kamek-pf** [fourmolu/fourmolu#91]
Hello !

Looks like monad comprehensions are currently unsupported. Support was implemented in Ourmolu a few months ago: https://github.com/tweag/ormolu/pull/666.

Would it be complicated to add this to Fourmolu ?

**Comment by brandonchinn178** [comment]
@kamek-pf Hi! Sorry for getting back so late. We just merged in all of ormolu's changes as of 0.3.0.1 (#106). We'll hopefully be making a release soon (#104), but feel free to pull down the `master` version of fourmolu and see if that works!

**Comment by kamek-pf** [comment]
These changes have been released for a while now, it's working as expected, thank you :D
